import type { AutogeneratedInsertableProjectImage } from '#schema/type/autogenerated/autogenerated_project_image.d.ts'
import type { TenantedWriteHelper } from '#shared/mysql/write_helper.ts'
import { fns } from '#shared/sql_request/mysql_function.ts'
import type { TransactionTenantedSelectBuilder } from '#worker/lib/db/make_tenanted_select_builder.ts'

export type ProjectImageBlobs = {
	original: AutogeneratedInsertableProjectImage['original_image']
	thumbnail: NonNullable<AutogeneratedInsertableProjectImage['thumbnail_image']>
	display: AutogeneratedInsertableProjectImage['display_image']
}

export const get_project_image_uploaded_at = async ({
	project_image_id,
	select_builder,
}: {
	project_image_id: bigint
	select_builder: TransactionTenantedSelectBuilder
}) => {
	const row = await select_builder.get_first_row(select_builder
		.from(`project_image`)
		.where(q => q.comparison(`project_image.project_image_id`, `=`, { value: project_image_id }))
		.select(() => [`project_image.uploaded_at`])
		.for_update()
		.build())

	return row === null ? null : { uploaded_at: row.project_image.uploaded_at }
}

export const store_project_image_blobs = async ({
	project_image_id,
	bytes,
	write_helper,
}: {
	project_image_id: bigint
	bytes: ProjectImageBlobs
	write_helper: TenantedWriteHelper
}): Promise<void> => {
	await write_helper.update(`project_image`, `project_image_id`, project_image_id, {
		original_image: bytes.original,
		thumbnail_image: bytes.thumbnail,
		display_image: bytes.display,
		uploaded_at: fns.utc_timestamp(),
	})
}
