name = "treebzns"
main = "src/worker/index.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-01-01"

routes = [
	{ pattern = "dufftreesoftware.com", custom_domain = true, zone_id = "f8be26c091ee3070d032517f29ced56c" }
]

[assets]
directory = "./src/public"
binding = "ASSETS"

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "02941f425bf3412ab5d4494740a22fc1"
