name = "treebzns"
account_id = "6f50bff84297ac787a97da4bb60aa20a"
main = "src/worker/index.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-01-01"

[assets]
directory = "./src/public"
binding = "ASSETS"

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "6c4d2f438cc342c99416bc41f2d07115"
