import type { MysqlHelpersObject } from '#worker/lib/mysql/mysql_helpers_object.ts'
import { create_employee } from '#worker/lib/employee.ts'
import { map } from '#shared/array.ts'
import { transaction } from '#worker/lib/mysql/helpers.ts'

const default_software_roles: {
	name: string
	permission_codes: DbPermission['code'][]
	owner?: true
}[] = [{
	name: 'Owner',
	permission_codes: ['CAN_CHANGE_WORK_ORDERS_WITHOUT_CUSTOMER_APPROVAL', 'CAN_CREATE_CLIENT', 'CAN_CREATE_ORDER', 'CAN_EDIT_CLIENT', 'CAN_EDIT_PAYMENTS', 'CAN_ESTIMATE', 'CAN_MANAGE_USERS', 'CAN_QUALIFY_LEAD', 'CAN_SET_ANY_DOCUMENT_STATUS', 'CAN_WORK_PROJECTS'],
	owner: true,
}, {
	name: 'Office',
	permission_codes: ['CAN_CREATE_CLIENT', 'CAN_CREATE_ORDER', 'CAN_EDIT_CLIENT', 'CAN_EDIT_PAYMENTS']
}, {
	name: 'Foreman',
	permission_codes: ['CAN_WORK_PROJECTS']
}, {
	name: 'Estimator',
	permission_codes: ['CAN_ESTIMATE', 'CAN_QUALIFY_LEAD']
}]

type CreateCompanyArg = Pick<AutogeneratedInsertableCompany, 'name'> & Partial<Omit<AutogeneratedInsertableCompany, 'name' | 'default_initial_project_document_id'>>

type OwnerEmployeeArg = Pick<AutogeneratedInsertableEmployee, 'name' | 'email'> & Partial<Pick<AutogeneratedInsertableEmployee, 'phone'>> & { password: string }

export const create_company = async (
	company: CreateCompanyArg,
	owner_employee: OwnerEmployeeArg,
	mysql: MysqlHelpersObject,
): Promise<bigint> => {
	return transaction(mysql.connection, async () => {
		const default_initial_project_document_id = await mysql.query(
			'SELECT project_document_id FROM project_document ORDER BY sort ASC LIMIT 1',
		).get_first_row_column<bigint>('project_document_id')

		const company_id = await mysql.query({
			sql: 'INSERT INTO company SET ?',
			values: {
				...company,
				default_initial_project_document_id,
			},
		}).get_insert_id()

		const permission_rows = await mysql.query('SELECT permission_id, code FROM permission').get_rows<{ permission_id: bigint, code: string }>()
		const permission_id_by_code = new Map(permission_rows.map(r => [r.code, r.permission_id]))

		let owner_software_role_id: bigint | null = null
		await Promise.all(map(default_software_roles, async role => {
			const software_role_id = await mysql.query({
				sql: 'INSERT INTO software_role SET ?',
				values: { company_id, name: role.name },
			}).get_insert_id()

			if (role.owner) {
				owner_software_role_id = software_role_id
			}

			const srp_rows = role.permission_codes.map(code => [company_id, software_role_id, permission_id_by_code.get(code)!])
			await mysql.query({
				sql: 'INSERT INTO software_role_permission (company_id, software_role_id, permission_id) VALUES ?',
				values: [srp_rows],
			})
		}))

		const employee_id = await create_employee({
			...owner_employee,
			company_id,
			is_owner: true,
			avatar_url: null,
			phone: owner_employee.phone ?? null,
		}, mysql)

		await mysql.query({
			sql: 'INSERT INTO employee_software_role SET ?',
			values: { company_id, employee_id, software_role_id: owner_software_role_id },
		})

		return company_id
	})
}
