import type { MysqlHelpersObject } from '#worker/lib/mysql/mysql_helpers_object.ts'
import { password_hash } from '#worker/lib/password_hash.ts'

export const DEFAULT_NUMBER_OF_PASSWORD_HASH_ITERATIONS = 50_000

type CreateEmployeeArg = Omit<AutogeneratedInsertableEmployee, 'password_hash' | 'number_of_password_hash_iterations'> & {
	password: string
}

export const create_employee = async (employee: CreateEmployeeArg, mysql: MysqlHelpersObject): Promise<bigint> => {
	const salt = employee.company_id
	const iterations = DEFAULT_NUMBER_OF_PASSWORD_HASH_ITERATIONS
	const hash_buffer = await password_hash(employee.password, salt, iterations)
	const hash_hex = Array.from(new Uint8Array(hash_buffer)).map(b => b.toString(16).padStart(2, '0')).join('')

	const { password: _, ...fields } = employee

	return mysql.query(
		'INSERT INTO employee SET ?',
		{
			...fields,
			password_hash: hash_hex,
			number_of_password_hash_iterations: iterations,
		},
	).get_insert_id()
}
