import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

declare global {
	type AutogeneratedInsertablePermission = {
		code: string
		name: string
	}

	type AutogeneratedPermission = {
		permission_id: bigint
		code: string
		name: string
		created_at: Temporal.Instant
		updated_at: Temporal.Instant
	}
}
