// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableCrewRegularHistory = {
	company_id: bigint
	crew_id: bigint
	employee_id: bigint
	action: string
	changed_by_employee_id: bigint | null
	change_date: Temporal.PlainDate
}

export type AutogeneratedCrewRegularHistory = {
	crew_regular_history_id: bigint
	company_id: bigint
	crew_id: bigint
	employee_id: bigint
	action: string
	changed_by_employee_id: bigint | null
	change_date: Temporal.PlainDate
	created_at: Temporal.Instant
}
