// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableClientClientTag = {
	company_id: bigint
	client_id: bigint
	client_tag_id: bigint
	created_by_employee_id: bigint
}

export type AutogeneratedClientClientTag = {
	client_client_tag_id: bigint
	company_id: bigint
	client_id: bigint
	client_tag_id: bigint
	created_by_employee_id: bigint
	created_at: Temporal.Instant
}
