import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

declare global {
	type AutogeneratedInsertableClientContact = {
		company_id: bigint
		client_id: bigint
		contact_name: string
		phone: string | null
		email: string | null
		is_primary: boolean
		sort_order: bigint
	}

	type AutogeneratedClientContact = {
		client_contact_id: bigint
		company_id: bigint
		client_id: bigint
		contact_name: string
		phone: string | null
		email: string | null
		is_primary: boolean
		sort_order: bigint
		created_at: Temporal.Instant
		updated_at: Temporal.Instant
	}
}
