import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableSoftwareRolePermission = {
	company_id: bigint
	software_role_id: bigint
	permission_id: bigint
}

export type AutogeneratedSoftwareRolePermission = {
	company_id: bigint
	software_role_id: bigint
	permission_id: bigint
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
}
