// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableInvoiceNumber = {
	company_id: bigint
	next_number: bigint
}

export type AutogeneratedInvoiceNumber = {
	invoice_number_id: bigint
	company_id: bigint
	next_number: bigint
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
}
