// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableProjectClientApproval = {
	company_id: bigint
	customer_signature: Buffer | null
	verbal_approval: boolean
	added_by_employee_id: bigint
}

export type AutogeneratedProjectClientApproval = {
	project_client_approval_id: bigint
	company_id: bigint
	customer_signature: Buffer | null
	verbal_approval: boolean
	added_by_employee_id: bigint
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
}
