// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertablePaymentInvoice = {
	company_id: bigint
	payment_id: bigint
	invoice_id: bigint
	amount: FinancialNumber
}

export type AutogeneratedPaymentInvoice = {
	payment_invoice_id: bigint
	company_id: bigint
	payment_id: bigint
	invoice_id: bigint
	amount: FinancialNumber
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
}
