// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableProjectDeclineReason = {
	company_id: bigint
	reason: string
}

export type AutogeneratedProjectDeclineReason = {
	project_decline_reason_id: bigint
	company_id: bigint
	reason: string
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
}
