// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableMigration = {
	migration_number: bigint
	ran_at: Temporal.Instant
}

export type AutogeneratedMigration = {
	migration_id: bigint
	migration_number: bigint
	ran_at: Temporal.Instant
}
