import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

declare global {
	type AutogeneratedInsertableEmployeeSession = {
		employee_id: bigint
		session_identifier: string
		enabled: boolean
	}

	type AutogeneratedEmployeeSession = {
		employee_session_id: bigint
		employee_id: bigint
		session_identifier: string
		enabled: boolean
		created_at: Temporal.Instant
		updated_at: Temporal.Instant
	}
}
