// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableClockSessionEmployeeHistory = {
	company_id: bigint
	clock_session_employee_id: bigint
	previous_clock_in: Temporal.Instant | null
	previous_clock_out: Temporal.Instant | null
	new_clock_in: Temporal.Instant | null
	new_clock_out: Temporal.Instant | null
	changed_by_employee_id: bigint | null
	change_date: Temporal.PlainDate
	change_datetime: Temporal.Instant
}

export type AutogeneratedClockSessionEmployeeHistory = {
	clock_session_employee_history_id: bigint
	company_id: bigint
	clock_session_employee_id: bigint
	previous_clock_in: Temporal.Instant | null
	previous_clock_out: Temporal.Instant | null
	new_clock_in: Temporal.Instant | null
	new_clock_out: Temporal.Instant | null
	changed_by_employee_id: bigint | null
	change_date: Temporal.PlainDate
	change_datetime: Temporal.Instant
	created_at: Temporal.Instant
}
