import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertablePayment = {
	company_id: bigint
	client_id: bigint
	amount: FinancialNumber
	payment_method: string
	status: string
}

export type AutogeneratedPayment = {
	payment_id: bigint
	company_id: bigint
	client_id: bigint
	amount: FinancialNumber
	payment_method: string
	status: string
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
}
