import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableEmployee = {
	company_id: bigint
	name: string
	email: string
	phone: string | null
	password_hash: string
	avatar_url: string | null
	is_owner: boolean
}

export type AutogeneratedEmployee = {
	employee_id: bigint
	company_id: bigint
	name: string
	email: string
	phone: string | null
	password_hash: string
	avatar_url: string | null
	is_owner: boolean
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
}
