// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableProjectImage = {
	company_id: bigint
	project_id: bigint
	original_object_key: string
	display_object_key: string
	thumbnail_object_key: string
	description: string
	visible_to_client: boolean
	uploaded_at: Temporal.Instant | null
	arbostar_image_id: bigint | null
	upload_employee_id: bigint | null
}

export type AutogeneratedProjectImage = {
	project_image_id: bigint
	company_id: bigint
	project_id: bigint
	original_object_key: string
	display_object_key: string
	thumbnail_object_key: string
	description: string
	visible_to_client: boolean
	uploaded_at: Temporal.Instant | null
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
	arbostar_image_id: bigint | null
	upload_employee_id: bigint | null
}
