// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableClockSessionEmployee = {
	company_id: bigint
	clock_session_id: bigint
	employee_id: bigint
	clock_in: Temporal.Instant
	clock_in_day: Temporal.PlainDate
	clock_out: Temporal.Instant | null
	clocked_in_by_employee_id: bigint
	clocked_out_by_employee_id: bigint | null
}

export type AutogeneratedClockSessionEmployee = {
	clock_session_employee_id: bigint
	company_id: bigint
	clock_session_id: bigint
	employee_id: bigint
	clock_in: Temporal.Instant
	clock_in_day: Temporal.PlainDate
	clock_out: Temporal.Instant | null
	clocked_in_by_employee_id: bigint
	clocked_out_by_employee_id: bigint | null
	open_employee_id: bigint | null
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
}
