// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableInvoiceLineItem = {
	company_id: bigint
	invoice_id: bigint
	project_line_item_id: bigint | null
	description: string
	quantity: FinancialNumber
	price: FinancialNumber
	discount_rate: FinancialNumber | null
	discount: FinancialNumber | null
	discount_description: string
	taxable: boolean
	sort: bigint
}

export type AutogeneratedInvoiceLineItem = {
	invoice_line_item_id: bigint
	company_id: bigint
	invoice_id: bigint
	project_line_item_id: bigint | null
	description: string
	quantity: FinancialNumber
	price: FinancialNumber
	discount_rate: FinancialNumber | null
	discount: FinancialNumber | null
	discount_description: string
	taxable: boolean
	sort: bigint
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
}
