// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableClientAddress = {
	company_id: bigint
	client_id: bigint
	name: string
	address_line_1: string
	address_line_2: string | null
	city: string
	state: string
	zip: string
	contact: string | null
	phone: string | null
	email: string | null
}

export type AutogeneratedClientAddress = {
	client_address_id: bigint
	company_id: bigint
	client_id: bigint
	name: string
	address_line_1: string
	address_line_2: string | null
	city: string
	state: string
	zip: string
	contact: string | null
	phone: string | null
	email: string | null
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
}
