import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableCompany = {
	name: string
	logo: Buffer | null
	brand_color: string
	default_initial_project_document_id: bigint
}

export type AutogeneratedCompany = {
	company_id: bigint
	name: string
	logo: Buffer | null
	brand_color: string
	default_initial_project_document_id: bigint
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
}
