import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

declare global {
	type AutogeneratedInsertableEmployeeSoftwareRole = {
		company_id: bigint
		employee_id: bigint
		software_role_id: bigint
	}

	type AutogeneratedEmployeeSoftwareRole = {
		employee_software_role_id: bigint
		company_id: bigint
		employee_id: bigint
		software_role_id: bigint
		created_at: Temporal.Instant
		updated_at: Temporal.Instant
	}
}
