import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableTaxRate = {
	company_id: bigint
	name: string
	tax_rate: FinancialNumber
}

export type AutogeneratedTaxRate = {
	tax_rate_id: bigint
	company_id: bigint
	name: string
	tax_rate: FinancialNumber
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
}
