// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableProjectCrewProjectLineItem = {
	company_id: bigint
	project_crew_id: bigint
	project_line_item_id: bigint
}

export type AutogeneratedProjectCrewProjectLineItem = {
	project_crew_project_line_item_id: bigint
	company_id: bigint
	project_crew_id: bigint
	project_line_item_id: bigint
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
}
