import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

declare global {
	type AutogeneratedInsertablePaymentProject = {
		company_id: bigint
		payment_id: bigint
		project_id: bigint
		amount: FinancialNumber
	}

	type AutogeneratedPaymentProject = {
		payment_project_id: bigint
		company_id: bigint
		payment_id: bigint
		project_id: bigint
		amount: FinancialNumber
		created_at: Temporal.Instant
		updated_at: Temporal.Instant
	}
}
