// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableClientContact = {
	company_id: bigint
	client_id: bigint
	contact_name: string
	phone: string | null
	email: string | null
	is_primary: boolean
	sort_order: bigint
	arbostar_contact_id: bigint | null
}

export type AutogeneratedClientContact = {
	client_contact_id: bigint
	company_id: bigint
	client_id: bigint
	contact_name: string
	phone: string | null
	email: string | null
	is_primary: boolean
	sort_order: bigint
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
	arbostar_contact_id: bigint | null
}
