// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableProjectImage = {
	company_id: bigint
	project_id: bigint
	original_image: Buffer
	display_image: Buffer | null
	description: string
	visible_to_client: boolean
}

export type AutogeneratedProjectImage = {
	project_image_id: bigint
	company_id: bigint
	project_id: bigint
	original_image: Buffer
	display_image: Buffer | null
	description: string
	visible_to_client: boolean
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
}
