import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableClient = {
	company_id: bigint
	name: string
	primary_client_address_id: bigint
	billing_client_address_id: bigint
	primary_phone: string | null
	primary_email: string | null
	tax_rate_id: bigint | null
	notes: string | null
	referred_by: string | null
}

export type AutogeneratedClient = {
	client_id: bigint
	company_id: bigint
	name: string
	primary_client_address_id: bigint
	billing_client_address_id: bigint
	primary_phone: string | null
	primary_email: string | null
	tax_rate_id: bigint | null
	notes: string | null
	referred_by: string | null
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
}
