// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertablePermission = {
	code: string
	name: string
}

export type AutogeneratedPermission = {
	permission_id: bigint
	code: string
	name: string
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
}
