import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

declare global {
	type AutogeneratedInsertableProjectNumber = {
		company_id: bigint
		last_number: bigint
	}

	type AutogeneratedProjectNumber = {
		project_number_id: bigint
		company_id: bigint
		last_number: bigint
		created_at: Temporal.Instant
		updated_at: Temporal.Instant
	}
}
