// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertablePayment = {
	company_id: bigint
	client_id: bigint
	amount: FinancialNumber
	payment_method_id: bigint
	arbostar_payment_id: bigint | null
}

export type AutogeneratedPayment = {
	payment_id: bigint
	company_id: bigint
	client_id: bigint
	amount: FinancialNumber
	payment_method_id: bigint
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
	arbostar_payment_id: bigint | null
}
