import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

declare global {
	type AutogeneratedInsertableCrewMember = {
		company_id: bigint
		crew_id: bigint
		employee_id: bigint
	}

	type AutogeneratedCrewMember = {
		company_id: bigint
		crew_id: bigint
		employee_id: bigint
		created_at: Temporal.Instant
		updated_at: Temporal.Instant
	}
}
