import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

declare global {
	type AutogeneratedInsertableItemType = {
		company_id: bigint
		name: string
		taxable: boolean
	}

	type AutogeneratedItemType = {
		item_type_id: bigint
		company_id: bigint
		name: string
		taxable: boolean
		created_at: Temporal.Instant
		updated_at: Temporal.Instant
	}
}
