import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

declare global {
	type AutogeneratedInsertableProjectLineItemImage = {
		company_id: bigint
		project_line_item_id: bigint
		image: Buffer
		description: string | null
	}

	type AutogeneratedProjectLineItemImage = {
		project_line_item_image_id: bigint
		company_id: bigint
		project_line_item_id: bigint
		image: Buffer
		description: string | null
		created_at: Temporal.Instant
		updated_at: Temporal.Instant
	}
}
