// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableProjectCrew = {
	company_id: bigint
	project_id: bigint
	crew_id: bigint
	work_date: Temporal.PlainDate
	day_order: bigint | null
	start_time: Temporal.PlainTime | null
}

export type AutogeneratedProjectCrew = {
	project_crew_id: bigint
	company_id: bigint
	project_id: bigint
	crew_id: bigint
	work_date: Temporal.PlainDate
	day_order: bigint | null
	start_time: Temporal.PlainTime | null
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
}
