import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableTimeEntry = {
	company_id: bigint
	employee_id: bigint
	project_id: bigint
	work_date: Temporal.PlainDate
	clock_in: Temporal.Instant
	clock_out: Temporal.Instant | null
	regular_hours: FinancialNumber
}

export type AutogeneratedTimeEntry = {
	time_entry_id: bigint
	company_id: bigint
	employee_id: bigint
	project_id: bigint
	work_date: Temporal.PlainDate
	clock_in: Temporal.Instant
	clock_out: Temporal.Instant | null
	regular_hours: FinancialNumber
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
}
