// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableCompany = {
	name: string
	logo: Buffer | null
	brand_color: string
	default_crew_start_time: Temporal.PlainTime
	invoice_due_after_days: bigint
	timezone: string
}

export type AutogeneratedCompany = {
	company_id: bigint
	name: string
	logo: Buffer | null
	brand_color: string
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
	default_crew_start_time: Temporal.PlainTime
	invoice_due_after_days: bigint
	timezone: string
}
