// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableClient = {
	company_id: bigint
	name: string
	is_commercial: boolean
	default_project_address_id: bigint | null
	default_billing_address_id: bigint | null
	primary_phone: string
	primary_email: string
	tax_rate_id: bigint | null
	notes: string
	referred_by: string
	arbostar_client_id: bigint | null
}

export type AutogeneratedClient = {
	client_id: bigint
	company_id: bigint
	name: string
	is_commercial: boolean
	default_project_address_id: bigint | null
	default_billing_address_id: bigint | null
	primary_phone: string
	primary_email: string
	tax_rate_id: bigint | null
	notes: string
	referred_by: string
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
	arbostar_client_id: bigint | null
}
