import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableProjectWorkSkill = {
	company_id: bigint
	project_id: bigint
	work_skill_id: bigint
}

export type AutogeneratedProjectWorkSkill = {
	project_work_skill_id: bigint
	company_id: bigint
	project_id: bigint
	work_skill_id: bigint
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
}
