// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableClientTag = {
	company_id: bigint
	name: string
	color: string
}

export type AutogeneratedClientTag = {
	client_tag_id: bigint
	company_id: bigint
	name: string
	color: string
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
}
