// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableProject = {
	company_id: bigint
	project_document_id: bigint
	number: bigint
	client_id: bigint
	client_address_id: bigint
	address_line_1: string
	address_line_2: string
	city: string
	state: string
	zip: string
	due_date: Temporal.PlainDate | null
	emergency: boolean
	assigned_estimator_employee_id: bigint | null
	lead_details: string
	created_by_employee_id: bigint
	needs_client_approval: boolean
	sent_for_client_approval: boolean
	taxable: boolean
	tax_rate_id: bigint | null
	tax_rate: FinancialNumber | null
	subtotal: FinancialNumber | null
	tax_total: FinancialNumber | null
	total: FinancialNumber | null
	notes_for_crew: string
	notes_for_office: string
	closed: boolean
	closed_at: Temporal.Instant | null
	closed_date: Temporal.PlainDate | null
	project_decline_reason_id: bigint | null
	lead_source: string
}

export type AutogeneratedProject = {
	project_id: bigint
	company_id: bigint
	project_document_id: bigint
	number: bigint
	client_id: bigint
	client_address_id: bigint
	address_line_1: string
	address_line_2: string
	city: string
	state: string
	zip: string
	due_date: Temporal.PlainDate | null
	emergency: boolean
	assigned_estimator_employee_id: bigint | null
	lead_details: string
	created_by_employee_id: bigint
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
	needs_client_approval: boolean
	sent_for_client_approval: boolean
	taxable: boolean
	tax_rate_id: bigint | null
	tax_rate: FinancialNumber | null
	subtotal: FinancialNumber | null
	tax_total: FinancialNumber | null
	total: FinancialNumber | null
	notes_for_crew: string
	notes_for_office: string
	closed: boolean
	closed_at: Temporal.Instant | null
	closed_date: Temporal.PlainDate | null
	project_decline_reason_id: bigint | null
	lead_source: string
}
