// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableProjectCrewEmployee = {
	company_id: bigint
	project_crew_id: bigint
	employee_id: bigint
}

export type AutogeneratedProjectCrewEmployee = {
	project_crew_employee_id: bigint
	company_id: bigint
	project_crew_id: bigint
	employee_id: bigint
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
}
