// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableEmployee = {
	company_id: bigint
	name: string
	email: string | null
	login_name: string | null
	phone: string
	password_hash: string
	is_owner: boolean
	number_of_password_hash_iterations: bigint
	arbostar_user_id: bigint | null
	default_crew_id: bigint | null
}

export type AutogeneratedEmployee = {
	employee_id: bigint
	company_id: bigint
	name: string
	email: string | null
	login_name: string | null
	phone: string
	password_hash: string
	is_owner: boolean
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
	number_of_password_hash_iterations: bigint
	arbostar_user_id: bigint | null
	default_crew_id: bigint | null
}
