import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

declare global {
	type AutogeneratedInsertableEmployeeSession = {
		employee_id: bigint
		identifier: Buffer
		invalidated: boolean
		sign_in_user_agent: string
		signed_in_at: Temporal.Instant
		last_seen_user_agent: string
		last_seen_at: Temporal.Instant
		expire_at: Temporal.Instant
	}

	type AutogeneratedEmployeeSession = {
		employee_session_id: bigint
		employee_id: bigint
		identifier: Buffer
		invalidated: boolean
		created_at: Temporal.Instant
		updated_at: Temporal.Instant
		sign_in_user_agent: string
		signed_in_at: Temporal.Instant
		last_seen_user_agent: string
		last_seen_at: Temporal.Instant
		expire_at: Temporal.Instant
	}
}
