// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertablePayment = {
	company_id: bigint
	client_id: bigint
	project_id: bigint | null
	amount: FinancialNumber
	tip: FinancialNumber
	merchant_fee: FinancialNumber
	pay_date: Temporal.PlainDate
	payment_method_id: bigint
	notes: string
	recorded_by_employee_id: bigint | null
	arbostar_payment_id: bigint | null
}

export type AutogeneratedPayment = {
	payment_id: bigint
	company_id: bigint
	client_id: bigint
	project_id: bigint | null
	amount: FinancialNumber
	tip: FinancialNumber
	merchant_fee: FinancialNumber
	pay_date: Temporal.PlainDate
	payment_method_id: bigint
	notes: string
	recorded_by_employee_id: bigint | null
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
	arbostar_payment_id: bigint | null
}
