// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableLeadSource = {
	company_id: bigint
	name: string
}

export type AutogeneratedLeadSource = {
	lead_source_id: bigint
	company_id: bigint
	name: string
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
}
