// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableLineItemTemplateWorkSkill = {
	company_id: bigint
	line_item_template_id: bigint
	work_skill_id: bigint
}

export type AutogeneratedLineItemTemplateWorkSkill = {
	line_item_template_work_skill_id: bigint
	company_id: bigint
	line_item_template_id: bigint
	work_skill_id: bigint
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
}
