// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableProjectNumber = {
	company_id: bigint
	last_number: bigint
}

export type AutogeneratedProjectNumber = {
	project_number_id: bigint
	company_id: bigint
	last_number: bigint
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
}
