// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableClientCredit = {
	company_id: bigint
	client_id: bigint
	amount: FinancialNumber
	notes: string
	created_by_employee_id: bigint
}

export type AutogeneratedClientCredit = {
	client_credit_id: bigint
	company_id: bigint
	client_id: bigint
	amount: FinancialNumber
	notes: string
	created_by_employee_id: bigint
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
}
