import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableCrewMember = {
	company_id: bigint
	crew_id: bigint
	employee_id: bigint
}

export type AutogeneratedCrewMember = {
	company_id: bigint
	crew_id: bigint
	employee_id: bigint
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
}
