import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

declare global {
	type AutogeneratedInsertableWorkSkill = {
		company_id: bigint
		name: string
		hourly_rate: FinancialNumber
	}

	type AutogeneratedWorkSkill = {
		work_skill_id: bigint
		company_id: bigint
		name: string
		hourly_rate: FinancialNumber
		created_at: Temporal.Instant
		updated_at: Temporal.Instant
	}
}
