// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableProjectLineItem = {
	company_id: bigint
	project_id: bigint
	title: string
	work_details: string | null
	item_type_id: bigint | null
	line_item_template_id: bigint | null
	estimated_hours: bigint
	taxable: boolean
	client_optional: boolean
	client_declined: boolean
	quantity: FinancialNumber
	price: FinancialNumber
	discount_rate: FinancialNumber | null
	discount: FinancialNumber | null
	discount_description: string
	sort: bigint
	done_at: Temporal.Instant | null
	done_by_employee_id: bigint | null
	arbostar_line_item_id: bigint | null
}

export type AutogeneratedProjectLineItem = {
	project_line_item_id: bigint
	company_id: bigint
	project_id: bigint
	title: string
	work_details: string | null
	item_type_id: bigint | null
	line_item_template_id: bigint | null
	estimated_hours: bigint
	taxable: boolean
	client_optional: boolean
	client_declined: boolean
	quantity: FinancialNumber
	price: FinancialNumber
	discount_rate: FinancialNumber | null
	discount: FinancialNumber | null
	discount_description: string
	sort: bigint
	done_at: Temporal.Instant | null
	done_by_employee_id: bigint | null
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
	arbostar_line_item_id: bigint | null
}
