import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableCrew = {
	company_id: bigint
	crew_leader_id: bigint
	color: string
}

export type AutogeneratedCrew = {
	crew_id: bigint
	company_id: bigint
	crew_leader_id: bigint
	color: string
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
}
