// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableClockSessionLineItem = {
	company_id: bigint
	clock_session_id: bigint
	project_line_item_id: bigint
}

export type AutogeneratedClockSessionLineItem = {
	clock_session_line_item_id: bigint
	company_id: bigint
	clock_session_id: bigint
	project_line_item_id: bigint
	created_at: Temporal.Instant
}
