// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableInvoice = {
	company_id: bigint
	invoice_number: bigint
	client_id: bigint
	project_id: bigint | null
	billing_name: string
	billing_address_line_1: string
	billing_address_line_2: string
	billing_city: string
	billing_state: string
	billing_zip: string
	invoice_date: Temporal.PlainDate
	due_date: Temporal.PlainDate
	taxable: boolean
	tax_rate_id: bigint | null
	tax_rate: FinancialNumber | null
	subtotal: FinancialNumber
	taxable_subtotal: FinancialNumber
	discount_rate: FinancialNumber | null
	discount: FinancialNumber | null
	discount_description: string
	line_item_discount_subtotal: FinancialNumber | null
	client_credit_applied: FinancialNumber
	tax_total: FinancialNumber
	fee: FinancialNumber
	total: FinancialNumber
	created_by_employee_id: bigint | null
	arbostar_invoice_id: bigint | null
}

export type AutogeneratedInvoice = {
	invoice_id: bigint
	company_id: bigint
	invoice_number: bigint
	client_id: bigint
	project_id: bigint | null
	billing_name: string
	billing_address_line_1: string
	billing_address_line_2: string
	billing_city: string
	billing_state: string
	billing_zip: string
	invoice_date: Temporal.PlainDate
	due_date: Temporal.PlainDate
	taxable: boolean
	tax_rate_id: bigint | null
	tax_rate: FinancialNumber | null
	subtotal: FinancialNumber
	taxable_subtotal: FinancialNumber
	discount_rate: FinancialNumber | null
	discount: FinancialNumber | null
	discount_description: string
	line_item_discount_subtotal: FinancialNumber | null
	client_credit_applied: FinancialNumber
	tax_total: FinancialNumber
	fee: FinancialNumber
	total: FinancialNumber
	created_by_employee_id: bigint | null
	arbostar_invoice_id: bigint | null
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
}
