// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableEstimateAvailability = {
	company_id: bigint
	project_id: bigint
	availability_date: Temporal.PlainDate
	start_time: Temporal.PlainTime
	end_time: Temporal.PlainTime
}

export type AutogeneratedEstimateAvailability = {
	estimate_availability_id: bigint
	company_id: bigint
	project_id: bigint
	availability_date: Temporal.PlainDate
	start_time: Temporal.PlainTime
	end_time: Temporal.PlainTime
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
}
