// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableLineItemTemplate = {
	company_id: bigint
	title: string
	arbostar_work_type_id: bigint | null
}

export type AutogeneratedLineItemTemplate = {
	line_item_template_id: bigint
	company_id: bigint
	title: string
	arbostar_work_type_id: bigint | null
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
}
