// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableProjectDocumentHistory = {
	company_id: bigint
	project_id: bigint
	project_document_id: bigint
	changed_by_employee_id: bigint | null
	change_date: Temporal.PlainDate
}

export type AutogeneratedProjectDocumentHistory = {
	project_document_history_id: bigint
	company_id: bigint
	project_id: bigint
	project_document_id: bigint
	changed_by_employee_id: bigint | null
	change_date: Temporal.PlainDate
	created_at: Temporal.Instant
}
