// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertableClockSession = {
	company_id: bigint
	project_id: bigint
	crew_id: bigint | null
	work_date: Temporal.PlainDate
	supersedes_clock_session_id: bigint | null
	notes: string
	opened_by_employee_id: bigint
}

export type AutogeneratedClockSession = {
	clock_session_id: bigint
	company_id: bigint
	project_id: bigint
	crew_id: bigint | null
	work_date: Temporal.PlainDate
	supersedes_clock_session_id: bigint | null
	notes: string
	opened_by_employee_id: bigint
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
}
