/*
Example output:

project:
project_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
company_id INT UNSIGNED NOT NULL,
project_document_id INT UNSIGNED NOT NULL,
client_id INT UNSIGNED NOT NULL,
client_address_id INT UNSIGNED NOT NULL,
address_line_1 VARCHAR(500),
address_line_2 VARCHAR(500),
city VARCHAR(100),
state VARCHAR(50),
zip VARCHAR(20),
due_date DATE,
emergency BIT(1),
assigned_estimator_employee_id INT UNSIGNED,
details TEXT,
created_by_employee_id INT UNSIGNED,
created_at DATETIME NOT NULL DEFAULT NOW(),
updated_at DATETIME NOT NULL DEFAULT NOW(),
needs_client_approval BIT(1) NOT NULL,
sent_for_client_approval BIT(1) NOT NULL,
tax_rate_id INT UNSIGNED,
tax_rate DECIMAL(6,4),
notes_for_crew TEXT,
notes_for_office TEXT,
closed BIT(1),
closed_at DATETIME,
closed_date DATE,

// output to schema/type/autogenerated/tax_rate.ts (overwrite on every run)
type AutogeneratedInsertableTaxRate = {
	company_id: BigInt
	name: string
	tax_rate: FinancialNumber
}

type AutogeneratedTaxRate = {
	tax_rate_id: BigInt
	company_id: BigInt
	name: string
	tax_rate: FinancialNumber
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
}

// output to schema/type/tax_rate.ts (only if the file does not exist already)
import { AutogeneratedInsertableTaxRate, AutogeneratedTaxRate } from './autogenerated/autogenerated_tax_rate'

declare global {
	type DbInsertableTaxRate = AutogeneratedInsertableTaxRate

	type DbTaxRate = AutogeneratedTaxRate
}


// output to schema/type/autogenerated/project.ts (overwrite on every run)
type AutogeneratedInsertableProject = {
	company_id: BigInt
	project_document_id: BigInt
	client_id: BigInt
	client_address_id: BigInt
	address_line_1: string
	address_line_2: string
	city: string
	state: string
	zip: string
	due_date: Temporal.PlainDate | null
	emergency: boolean
	assigned_estimator_employee_id: BigInt | null
	details: string
	created_by_employee_id: BigInt
	needs_client_approval: boolean
	sent_for_client_approval: boolean
	tax_rate_id: BigInt | null
	tax_rate: FinancialNumber
	notes_for_crew: string
	notes_for_office: string
	closed: boolean
	closed_at: Temporal.Instant | null
	closed_date: Temporal.PlainDate | null
}

type AutogeneratedProject = {
	project_id: BigInt
	company_id: BigInt
	project_document_id: BigInt
	client_id: BigInt
	client_address_id: BigInt
	address_line_1: string
	address_line_2: string
	city: string
	state: string
	zip: string
	due_date: Temporal.PlainDate | null
	emergency: boolean
	assigned_estimator_employee_id: BigInt | null
	details: string
	created_by_employee_id: BigInt
	created_at: Temporal.Instant
	updated_at: Temporal.Instant
	needs_client_approval: boolean
	sent_for_client_approval: boolean
	tax_rate_id: BigInt | null
	tax_rate: FinancialNumber
	notes_for_crew: string
	notes_for_office: string
	closed: boolean
	closed_at: Temporal.Instant | null
	closed_date: Temporal.PlainDate | null
}

// output to schema/type/project.ts (only if the file does not exist already)
import { AutogeneratedInsertableProject, AutogeneratedProject } from './autogenerated/autogenerated_project'

declare global {
	type DbInsertableProject = AutogeneratedInsertableProject

	type DbProject = AutogeneratedProject
}

// output to schema/constants.ts
export const schema = {
	tax_rate: {
		tax_rate_id: 'tax_rate_id',
		company_id: 'company_id',
		name: 'name',
		tax_rate: 'tax_rate',
		created_at: 'created_at',
		updated_at: 'updated_at',
	},
	project: 'project',
		project_id: 'project_id',
		company_id: 'company_id',
		project_document_id: 'project_document_id',
		client_id: 'client_id',
		client_address_id: 'client_address_id',
		address_line_1: 'address_line_1',
		address_line_2: 'address_line_2',
		city: 'city',
		state: 'state',
		zip: 'zip',
		due_date: 'due_date',
		emergency: 'emergency',
		assigned_estimator_employee_id: 'assigned_estimator_employee_id',
		details: 'details',
		created_by_employee_id: 'created_by_employee_id',
		created_at: 'created_at',
		updated_at: 'updated_at',
		needs_client_approval: 'needs_client_approval',
		sent_for_client_approval: 'sent_for_client_approval',
		tax_rate_id: 'tax_rate_id',
		tax_rate: 'tax_rate',
		notes_for_crew: 'notes_for_crew',
		notes_for_office: 'notes_for_office',
		closed: 'closed',
		closed_at: 'closed_at',
		closed_date: 'closed_date',
	}
} as const

*/
