// AUTO-GENERATED by scripts/generate_server_function_types.ts — do not edit by hand.
import f3tch from '#shared/f3tch.ts'
import type { Temporal } from '@js-temporal/polyfill'
import type { OptionalizeUndefinedKeys } from '#shared/json_validator.ts'
import type { SafeSelectQuery } from '#shared/sql_request/safe_select_query_validator.ts'
import type { LeadAddress, LeadBilling, LeadClient, LeadContact } from '#shared/type/lead.ts'

const call_server_function = (function_name: string) => async (arg: unknown) => f3tch(`/api/fn/${function_name}`, {
	method: 'POST',
	body: arg,
})

const server_functions: {
	create_client: (arg: OptionalizeUndefinedKeys<{ readonly name: string; readonly is_commercial: boolean; readonly primary_phone: string; readonly primary_email: string; readonly tax_rate_id: bigint | null | undefined; readonly notes: string; readonly referred_by: string; readonly primary_address: OptionalizeUndefinedKeys<{ readonly name: string; readonly address_line_1: string; readonly address_line_2: string; readonly city: string; readonly state: string; readonly zip: string; }>; }>) => Promise<Pick<DbClient, "client_id" | "default_project_address_id">>
	create_company: (arg: OptionalizeUndefinedKeys<{ name: string; }>) => Promise<Pick<DbCompany, "name" | "company_id">>
	create_lead: (arg: { client: LeadClient; billing_address: LeadBilling | null; address: LeadAddress; contact: LeadContact; project: { due_date: Temporal.PlainDate | null; emergency: boolean; lead_details: string; notes_for_crew: string; notes_for_office: string; assigned_estimator_employee_id: bigint | null; } & ({ lead_source_id: bigint; lead_source_name: null; } | { lead_source_id: null; lead_source_name: string | null; }); availability: { availability_date: Temporal.PlainDate; start_time: Temporal.PlainTime; end_time: Temporal.PlainTime; }[]; }) => Promise<{ project_id: bigint; client_id: bigint; }>
	query: (arg: SafeSelectQuery) => Promise<unknown[][]>
	ping: (arg: OptionalizeUndefinedKeys<{ readonly timeout: 1000n | 2000n | 3000n; }>) => Promise<{ pong: boolean; user_id: bigint; }>
} = {
	create_client: call_server_function('create_client'),
	create_company: call_server_function('create_company'),
	create_lead: call_server_function('create_lead'),
	query: call_server_function('query'),
	ping: call_server_function('ping'),
}

export default server_functions
