ALTER TABLE client_contact
	CHANGE COLUMN sort_order sort SMALLINT UNSIGNED NOT NULL;

ALTER TABLE invoice_line_item
	MODIFY COLUMN sort SMALLINT UNSIGNED NOT NULL;

ALTER TABLE project_document
	MODIFY COLUMN sort SMALLINT UNSIGNED NOT NULL;

ALTER TABLE project_line_item
	MODIFY COLUMN sort SMALLINT UNSIGNED NOT NULL;
