// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

export const client = {
	client_id: 'client_id',
	company_id: 'company_id',
	name: 'name',
	primary_client_address_id: 'primary_client_address_id',
	billing_client_address_id: 'billing_client_address_id',
	primary_phone: 'primary_phone',
	primary_email: 'primary_email',
	tax_rate_id: 'tax_rate_id',
	notes: 'notes',
	referred_by: 'referred_by',
	created_at: 'created_at',
	updated_at: 'updated_at',
} as const

export const client_address = {
	client_address_id: 'client_address_id',
	company_id: 'company_id',
	client_id: 'client_id',
	name: 'name',
	address_line_1: 'address_line_1',
	address_line_2: 'address_line_2',
	city: 'city',
	state: 'state',
	zip: 'zip',
	contact: 'contact',
	phone: 'phone',
	email: 'email',
	created_at: 'created_at',
	updated_at: 'updated_at',
} as const

export const client_contact = {
	client_contact_id: 'client_contact_id',
	company_id: 'company_id',
	client_id: 'client_id',
	contact_name: 'contact_name',
	phone: 'phone',
	email: 'email',
	is_primary: 'is_primary',
	sort_order: 'sort_order',
	created_at: 'created_at',
	updated_at: 'updated_at',
} as const

export const company = {
	company_id: 'company_id',
	name: 'name',
	logo: 'logo',
	brand_color: 'brand_color',
	default_initial_project_document_id: 'default_initial_project_document_id',
	created_at: 'created_at',
	updated_at: 'updated_at',
} as const

export const crew = {
	crew_id: 'crew_id',
	company_id: 'company_id',
	crew_leader_id: 'crew_leader_id',
	color: 'color',
	created_at: 'created_at',
	updated_at: 'updated_at',
} as const

export const crew_member = {
	company_id: 'company_id',
	crew_id: 'crew_id',
	employee_id: 'employee_id',
	created_at: 'created_at',
	updated_at: 'updated_at',
} as const

export const employee = {
	employee_id: 'employee_id',
	company_id: 'company_id',
	name: 'name',
	email: 'email',
	phone: 'phone',
	password_hash: 'password_hash',
	is_owner: 'is_owner',
	created_at: 'created_at',
	updated_at: 'updated_at',
	number_of_password_hash_iterations: 'number_of_password_hash_iterations',
} as const

export const employee_session = {
	employee_session_id: 'employee_session_id',
	employee_id: 'employee_id',
	identifier: 'identifier',
	invalidated: 'invalidated',
	created_at: 'created_at',
	updated_at: 'updated_at',
	sign_in_user_agent: 'sign_in_user_agent',
	signed_in_at: 'signed_in_at',
	last_seen_user_agent: 'last_seen_user_agent',
	last_seen_at: 'last_seen_at',
} as const

export const employee_software_role = {
	employee_software_role_id: 'employee_software_role_id',
	company_id: 'company_id',
	employee_id: 'employee_id',
	software_role_id: 'software_role_id',
	created_at: 'created_at',
	updated_at: 'updated_at',
} as const

export const estimate_availability = {
	estimate_availability_id: 'estimate_availability_id',
	company_id: 'company_id',
	project_id: 'project_id',
	availability_date: 'availability_date',
	start_time: 'start_time',
	end_time: 'end_time',
	created_at: 'created_at',
	updated_at: 'updated_at',
} as const

export const item_type = {
	item_type_id: 'item_type_id',
	company_id: 'company_id',
	name: 'name',
	taxable: 'taxable',
	created_at: 'created_at',
	updated_at: 'updated_at',
} as const

export const migration = {
	migration_id: 'migration_id',
	migration_number: 'migration_number',
	ran_at: 'ran_at',
} as const

export const payment = {
	payment_id: 'payment_id',
	company_id: 'company_id',
	client_id: 'client_id',
	amount: 'amount',
	payment_method: 'payment_method',
	status: 'status',
	created_at: 'created_at',
	updated_at: 'updated_at',
} as const

export const payment_project = {
	payment_project_id: 'payment_project_id',
	company_id: 'company_id',
	payment_id: 'payment_id',
	project_id: 'project_id',
	amount: 'amount',
	created_at: 'created_at',
	updated_at: 'updated_at',
} as const

export const permission = {
	permission_id: 'permission_id',
	code: 'code',
	name: 'name',
	created_at: 'created_at',
	updated_at: 'updated_at',
} as const

export const project = {
	project_id: 'project_id',
	company_id: 'company_id',
	project_document_id: 'project_document_id',
	client_id: 'client_id',
	client_address_id: 'client_address_id',
	address_line_1: 'address_line_1',
	address_line_2: 'address_line_2',
	city: 'city',
	state: 'state',
	zip: 'zip',
	due_date: 'due_date',
	emergency: 'emergency',
	assigned_estimator_employee_id: 'assigned_estimator_employee_id',
	lead_details: 'lead_details',
	created_by_employee_id: 'created_by_employee_id',
	created_at: 'created_at',
	updated_at: 'updated_at',
	needs_client_approval: 'needs_client_approval',
	sent_for_client_approval: 'sent_for_client_approval',
	tax_rate_id: 'tax_rate_id',
	tax_rate: 'tax_rate',
	notes_for_crew: 'notes_for_crew',
	notes_for_office: 'notes_for_office',
	closed: 'closed',
	closed_at: 'closed_at',
	closed_date: 'closed_date',
	lead_source: 'lead_source',
} as const

export const project_client_approval = {
	project_client_approval_id: 'project_client_approval_id',
	company_id: 'company_id',
	customer_signature: 'customer_signature',
	verbal_approval: 'verbal_approval',
	added_by_employee_id: 'added_by_employee_id',
	created_at: 'created_at',
	updated_at: 'updated_at',
} as const

export const project_document = {
	project_document_id: 'project_document_id',
	name: 'name',
	needs_estimate_to_move_on: 'needs_estimate_to_move_on',
	needs_client_approval_to_move_on: 'needs_client_approval_to_move_on',
	can_expire: 'can_expire',
	expire_days: 'expire_days',
	next_project_document_id: 'next_project_document_id',
	should_be_worked: 'should_be_worked',
	needs_to_be_contacted_by_lead_qualifier: 'needs_to_be_contacted_by_lead_qualifier',
	can_be_closed: 'can_be_closed',
	represents_billable_sale_when_closed: 'represents_billable_sale_when_closed',
	created_at: 'created_at',
	updated_at: 'updated_at',
	sort: 'sort',
} as const

export const project_line_item = {
	project_line_item_id: 'project_line_item_id',
	company_id: 'company_id',
	project_id: 'project_id',
	description: 'description',
	item_type_id: 'item_type_id',
	estimated_hours: 'estimated_hours',
	taxable: 'taxable',
	quantity: 'quantity',
	price: 'price',
	created_at: 'created_at',
	updated_at: 'updated_at',
} as const

export const project_line_item_image = {
	project_line_item_image_id: 'project_line_item_image_id',
	company_id: 'company_id',
	project_line_item_id: 'project_line_item_id',
	image: 'image',
	description: 'description',
	created_at: 'created_at',
	updated_at: 'updated_at',
} as const

export const project_number = {
	project_number_id: 'project_number_id',
	company_id: 'company_id',
	last_number: 'last_number',
	created_at: 'created_at',
	updated_at: 'updated_at',
} as const

export const project_work_skill = {
	project_work_skill_id: 'project_work_skill_id',
	company_id: 'company_id',
	project_id: 'project_id',
	work_skill_id: 'work_skill_id',
	created_at: 'created_at',
	updated_at: 'updated_at',
} as const

export const software_role = {
	software_role_id: 'software_role_id',
	company_id: 'company_id',
	name: 'name',
	created_at: 'created_at',
	updated_at: 'updated_at',
} as const

export const software_role_permission = {
	company_id: 'company_id',
	software_role_id: 'software_role_id',
	permission_id: 'permission_id',
	created_at: 'created_at',
	updated_at: 'updated_at',
} as const

export const tax_rate = {
	tax_rate_id: 'tax_rate_id',
	company_id: 'company_id',
	name: 'name',
	tax_rate: 'tax_rate',
	created_at: 'created_at',
	updated_at: 'updated_at',
} as const

export const time_entry = {
	time_entry_id: 'time_entry_id',
	company_id: 'company_id',
	employee_id: 'employee_id',
	project_id: 'project_id',
	work_date: 'work_date',
	clock_in: 'clock_in',
	clock_out: 'clock_out',
	regular_hours: 'regular_hours',
	created_at: 'created_at',
	updated_at: 'updated_at',
} as const

export const work_skill = {
	work_skill_id: 'work_skill_id',
	company_id: 'company_id',
	name: 'name',
	hourly_rate: 'hourly_rate',
	created_at: 'created_at',
	updated_at: 'updated_at',
} as const
