-- AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

CREATE TABLE `client` (
  `client_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `name` varchar(500) COLLATE utf8mb4_general_ci NOT NULL,
  `is_commercial` bit(1) NOT NULL DEFAULT b'0',
  `default_project_address_id` int unsigned DEFAULT NULL,
  `default_billing_address_id` int unsigned DEFAULT NULL,
  `primary_phone` varchar(30) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `primary_email` varchar(500) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `tax_rate_id` int unsigned DEFAULT NULL,
  `notes` text COLLATE utf8mb4_general_ci NOT NULL DEFAULT (_utf8mb4''),
  `referred_by` varchar(500) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `arbostar_client_id` int unsigned DEFAULT NULL,
  PRIMARY KEY (`client_id`),
  UNIQUE KEY `uq_client_company_arbostar_client_id` (`company_id`,`arbostar_client_id`),
  KEY `idx_client_tax_rate` (`tax_rate_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `client_address` (
  `client_address_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `client_id` int unsigned NOT NULL,
  `name` varchar(200) COLLATE utf8mb4_general_ci NOT NULL,
  `address_line_1` varchar(500) COLLATE utf8mb4_general_ci NOT NULL,
  `address_line_2` varchar(500) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `city` varchar(100) COLLATE utf8mb4_general_ci NOT NULL,
  `state` varchar(50) COLLATE utf8mb4_general_ci NOT NULL,
  `zip` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `contact` varchar(500) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `phone` varchar(50) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `email` varchar(500) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `sort_order` smallint NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `latitude` double DEFAULT NULL,
  `longitude` double DEFAULT NULL,
  PRIMARY KEY (`client_address_id`),
  KEY `idx_client_address_client` (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `client_contact` (
  `client_contact_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `client_id` int unsigned NOT NULL,
  `description` varchar(200) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `name` varchar(200) COLLATE utf8mb4_general_ci NOT NULL,
  `phone` varchar(30) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `email` varchar(500) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `arbostar_email_data` json DEFAULT NULL,
  `is_primary` bit(1) NOT NULL DEFAULT b'0',
  `sort_order` smallint NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `arbostar_contact_id` int unsigned DEFAULT NULL,
  PRIMARY KEY (`client_contact_id`),
  UNIQUE KEY `uq_client_contact_company_arbostar_contact_id` (`company_id`,`arbostar_contact_id`),
  KEY `idx_client_contact_client` (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `client_credit` (
  `client_credit_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `client_id` int unsigned NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `notes` varchar(500) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `created_by_employee_id` int unsigned NOT NULL,
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`client_credit_id`),
  KEY `idx_client_credit_client` (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `company` (
  `company_id` int unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(500) COLLATE utf8mb4_general_ci NOT NULL,
  `logo` blob,
  `brand_color` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `default_crew_start_time` time NOT NULL DEFAULT '08:00:00',
  `invoice_due_after_days` int unsigned NOT NULL DEFAULT '30',
  PRIMARY KEY (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `crew` (
  `crew_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `name` varchar(100) COLLATE utf8mb4_general_ci NOT NULL,
  `color` varchar(7) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '#000000',
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`crew_id`),
  KEY `idx_crew_company` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `crew_regular` (
  `company_id` int unsigned NOT NULL,
  `crew_id` int unsigned NOT NULL,
  `employee_id` int unsigned NOT NULL,
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`crew_id`,`employee_id`),
  KEY `idx_crew_regular_employee` (`employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `crew_regular_history` (
  `crew_regular_history_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `crew_id` int unsigned NOT NULL,
  `employee_id` int unsigned NOT NULL,
  `action` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `changed_by_employee_id` int unsigned DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`crew_regular_history_id`),
  KEY `idx_crew_regular_history_crew` (`crew_id`),
  KEY `idx_crew_regular_history_employee` (`employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `employee` (
  `employee_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `name` varchar(100) COLLATE utf8mb4_general_ci NOT NULL,
  `email` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `login_name` varchar(200) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `phone` varchar(30) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `password_hash` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `is_owner` bit(1) NOT NULL,
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `number_of_password_hash_iterations` int unsigned NOT NULL,
  `arbostar_user_id` int unsigned DEFAULT NULL,
  `default_crew_id` int unsigned DEFAULT NULL,
  PRIMARY KEY (`employee_id`),
  UNIQUE KEY `uq_employee_email` (`email`),
  UNIQUE KEY `uq_employee_login_name` (`login_name`),
  UNIQUE KEY `uq_employee_company_arbostar_user_id` (`company_id`,`arbostar_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `employee_session` (
  `employee_session_id` int unsigned NOT NULL AUTO_INCREMENT,
  `employee_id` int unsigned NOT NULL,
  `identifier` binary(16) NOT NULL,
  `invalidated` bit(1) NOT NULL DEFAULT b'0',
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `sign_in_user_agent` text COLLATE utf8mb4_general_ci NOT NULL,
  `signed_in_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `last_seen_user_agent` text COLLATE utf8mb4_general_ci NOT NULL,
  `last_seen_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`employee_session_id`),
  UNIQUE KEY `uq_employee_session_identifier` (`identifier`),
  KEY `idx_employee_session_employee` (`employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `employee_software_role` (
  `employee_software_role_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `employee_id` int unsigned NOT NULL,
  `software_role_id` int unsigned NOT NULL,
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`employee_software_role_id`),
  KEY `idx_esr_employee` (`employee_id`),
  KEY `idx_esr_software_role` (`software_role_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `employee_work_skill` (
  `employee_work_skill_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `employee_id` int unsigned NOT NULL,
  `work_skill_id` int unsigned NOT NULL,
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`employee_work_skill_id`),
  UNIQUE KEY `uq_employee_work_skill_employee_work_skill` (`employee_id`,`work_skill_id`),
  KEY `idx_employee_work_skill_work_skill` (`work_skill_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `estimate_availability` (
  `estimate_availability_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `project_id` int unsigned NOT NULL,
  `availability_date` date NOT NULL,
  `start_time` time NOT NULL,
  `end_time` time NOT NULL,
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`estimate_availability_id`),
  KEY `idx_estimate_availability_project` (`project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `invoice` (
  `invoice_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `invoice_number` int unsigned NOT NULL,
  `client_id` int unsigned NOT NULL,
  `project_id` int unsigned DEFAULT NULL,
  `billing_name` varchar(500) COLLATE utf8mb4_general_ci NOT NULL,
  `billing_address_line_1` varchar(500) COLLATE utf8mb4_general_ci NOT NULL,
  `billing_address_line_2` varchar(500) COLLATE utf8mb4_general_ci NOT NULL,
  `billing_city` varchar(100) COLLATE utf8mb4_general_ci NOT NULL,
  `billing_state` varchar(50) COLLATE utf8mb4_general_ci NOT NULL,
  `billing_zip` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `invoice_date` date NOT NULL,
  `due_date` date NOT NULL,
  `taxable` bit(1) NOT NULL,
  `tax_rate_id` int unsigned DEFAULT NULL,
  `tax_rate` decimal(4,4) DEFAULT NULL,
  `subtotal` decimal(10,2) NOT NULL,
  `taxable_subtotal` decimal(10,2) NOT NULL,
  `discount` decimal(10,2) DEFAULT NULL,
  `line_item_discount_subtotal` decimal(10,2) DEFAULT NULL,
  `client_credit_applied` decimal(10,2) NOT NULL DEFAULT '0.00',
  `tax_total` decimal(10,2) NOT NULL,
  `fee` decimal(10,2) NOT NULL DEFAULT '0.00',
  `total` decimal(10,2) NOT NULL,
  `created_by_employee_id` int unsigned DEFAULT NULL,
  `arbostar_invoice_id` int unsigned DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`invoice_id`),
  UNIQUE KEY `uq_invoice_company_number` (`company_id`,`invoice_number`),
  UNIQUE KEY `uq_invoice_company_arbostar_invoice_id` (`company_id`,`arbostar_invoice_id`),
  KEY `idx_invoice_client` (`client_id`),
  KEY `idx_invoice_project` (`project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `invoice_line_item` (
  `invoice_line_item_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `invoice_id` int unsigned NOT NULL,
  `project_line_item_id` int unsigned DEFAULT NULL,
  `description` varchar(200) COLLATE utf8mb4_general_ci NOT NULL,
  `quantity` decimal(10,2) NOT NULL,
  `price` decimal(10,2) NOT NULL,
  `discount_rate` decimal(5,4) DEFAULT NULL,
  `discount` decimal(10,2) DEFAULT NULL,
  `taxable` bit(1) NOT NULL,
  `sort` int unsigned NOT NULL,
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`invoice_line_item_id`),
  KEY `idx_ili_invoice` (`invoice_id`),
  KEY `idx_ili_project_line_item` (`project_line_item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `invoice_number` (
  `invoice_number_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `next_number` int unsigned NOT NULL DEFAULT '1',
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`invoice_number_id`),
  UNIQUE KEY `uq_invoice_number_company` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `item_type` (
  `item_type_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `name` varchar(100) COLLATE utf8mb4_general_ci NOT NULL,
  `taxable` bit(1) NOT NULL DEFAULT b'0',
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`item_type_id`),
  UNIQUE KEY `uq_item_type_company_name` (`company_id`,`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `line_item_template` (
  `line_item_template_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `title` varchar(200) COLLATE utf8mb4_general_ci NOT NULL,
  `estimated_hours` int unsigned DEFAULT NULL,
  `price` decimal(10,2) DEFAULT NULL,
  `arbostar_work_type_id` int unsigned DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`line_item_template_id`),
  UNIQUE KEY `uq_line_item_template_company_title` (`company_id`,`title`),
  UNIQUE KEY `uq_line_item_template_company_arbostar_work_type_id` (`company_id`,`arbostar_work_type_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `line_item_template_work_skill` (
  `line_item_template_work_skill_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `line_item_template_id` int unsigned NOT NULL,
  `work_skill_id` int unsigned NOT NULL,
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`line_item_template_work_skill_id`),
  UNIQUE KEY `uq_litws_line_item_template_work_skill` (`line_item_template_id`,`work_skill_id`),
  KEY `idx_litws_work_skill` (`work_skill_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `migration` (
  `migration_id` int unsigned NOT NULL AUTO_INCREMENT,
  `migration_number` int unsigned NOT NULL,
  `ran_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`migration_id`),
  UNIQUE KEY `uq_migration_number` (`migration_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `payment` (
  `payment_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `client_id` int unsigned NOT NULL,
  `project_id` int unsigned DEFAULT NULL,
  `amount` decimal(12,2) NOT NULL,
  `tip` decimal(10,2) NOT NULL DEFAULT '0.00',
  `merchant_fee` decimal(10,2) NOT NULL DEFAULT '0.00',
  `pay_date` date NOT NULL,
  `payment_method_id` int unsigned NOT NULL,
  `notes` varchar(500) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `recorded_by_employee_id` int unsigned DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `arbostar_payment_id` int unsigned DEFAULT NULL,
  PRIMARY KEY (`payment_id`),
  UNIQUE KEY `uq_payment_company_arbostar_payment_id` (`company_id`,`arbostar_payment_id`),
  KEY `idx_payment_client` (`client_id`),
  KEY `idx_payment_project` (`project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `payment_invoice` (
  `payment_invoice_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `payment_id` int unsigned NOT NULL,
  `invoice_id` int unsigned NOT NULL,
  `amount` decimal(12,2) NOT NULL,
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`payment_invoice_id`),
  UNIQUE KEY `uq_payment_invoice` (`payment_id`,`invoice_id`),
  KEY `idx_payment_invoice_invoice` (`invoice_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `payment_method` (
  `payment_method_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `name` varchar(100) COLLATE utf8mb4_general_ci NOT NULL,
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`payment_method_id`),
  UNIQUE KEY `uq_payment_method_company_name` (`company_id`,`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `permission` (
  `permission_id` int unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `name` varchar(200) COLLATE utf8mb4_general_ci NOT NULL,
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`permission_id`),
  UNIQUE KEY `uq_permission_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `project` (
  `project_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `project_document_id` int unsigned NOT NULL,
  `number` int unsigned NOT NULL,
  `client_id` int unsigned NOT NULL,
  `client_address_id` int unsigned NOT NULL,
  `address_line_1` varchar(500) COLLATE utf8mb4_general_ci NOT NULL,
  `address_line_2` varchar(500) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `city` varchar(100) COLLATE utf8mb4_general_ci NOT NULL,
  `state` varchar(50) COLLATE utf8mb4_general_ci NOT NULL,
  `zip` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `due_date` date DEFAULT NULL,
  `emergency` bit(1) NOT NULL DEFAULT b'0',
  `assigned_estimator_employee_id` int unsigned DEFAULT NULL,
  `lead_details` text COLLATE utf8mb4_general_ci NOT NULL DEFAULT (_utf8mb4''),
  `created_by_employee_id` int unsigned NOT NULL,
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `needs_client_approval` bit(1) NOT NULL,
  `sent_for_client_approval` bit(1) NOT NULL,
  `taxable` bit(1) NOT NULL DEFAULT b'0',
  `tax_rate_id` int unsigned DEFAULT NULL,
  `tax_rate` decimal(4,4) DEFAULT NULL,
  `subtotal` decimal(10,2) DEFAULT NULL,
  `taxable_subtotal` decimal(10,2) DEFAULT NULL,
  `discount` decimal(10,2) DEFAULT NULL,
  `line_item_discount_subtotal` decimal(10,2) DEFAULT NULL,
  `tax_total` decimal(10,2) DEFAULT NULL,
  `total` decimal(10,2) DEFAULT NULL,
  `notes_for_crew` text COLLATE utf8mb4_general_ci NOT NULL DEFAULT (_utf8mb4''),
  `notes_for_office` text COLLATE utf8mb4_general_ci NOT NULL DEFAULT (_utf8mb4''),
  `closed` bit(1) NOT NULL DEFAULT b'0',
  `closed_at` datetime DEFAULT NULL,
  `closed_date` date DEFAULT NULL,
  `project_decline_reason_id` int unsigned DEFAULT NULL,
  `lead_source` varchar(500) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `contact_name` varchar(500) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `contact_phone` varchar(30) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `contact_email` varchar(500) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `latitude` double DEFAULT NULL,
  `longitude` double DEFAULT NULL,
  PRIMARY KEY (`project_id`),
  UNIQUE KEY `uq_project_company_number` (`company_id`,`number`),
  KEY `idx_project_company_document` (`company_id`,`project_document_id`),
  KEY `idx_project_company_closed` (`company_id`,`closed`,`closed_date`),
  KEY `idx_project_company_estimator` (`company_id`,`assigned_estimator_employee_id`),
  KEY `idx_project_client` (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `project_client_approval` (
  `project_client_approval_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `project_id` int unsigned NOT NULL,
  `customer_signature` blob,
  `verbal_approval` bit(1) NOT NULL,
  `added_by_employee_id` int unsigned NOT NULL,
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`project_client_approval_id`),
  KEY `idx_pca_employee` (`added_by_employee_id`),
  KEY `idx_pca_project` (`project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `project_crew` (
  `project_crew_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `project_id` int unsigned NOT NULL,
  `crew_id` int unsigned NOT NULL,
  `work_date` date NOT NULL,
  `day_order` tinyint unsigned DEFAULT NULL,
  `start_time` time DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`project_crew_id`),
  UNIQUE KEY `uq_project_crew_project_crew_work_date` (`project_id`,`crew_id`,`work_date`),
  UNIQUE KEY `uq_project_crew_crew_work_date_day_order` (`crew_id`,`work_date`,`day_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `project_crew_employee` (
  `project_crew_employee_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `project_crew_id` int unsigned NOT NULL,
  `employee_id` int unsigned NOT NULL,
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`project_crew_employee_id`),
  UNIQUE KEY `uq_project_crew_employee_project_crew_employee` (`project_crew_id`,`employee_id`),
  KEY `idx_project_crew_employee_employee` (`employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `project_crew_project_line_item` (
  `project_crew_project_line_item_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `project_crew_id` int unsigned NOT NULL,
  `project_line_item_id` int unsigned NOT NULL,
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`project_crew_project_line_item_id`),
  UNIQUE KEY `uq_pcpli_project_crew_project_line_item` (`project_crew_id`,`project_line_item_id`),
  KEY `idx_pcpli_project_line_item` (`project_line_item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `project_decline_reason` (
  `project_decline_reason_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `reason` varchar(200) COLLATE utf8mb4_general_ci NOT NULL,
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`project_decline_reason_id`),
  UNIQUE KEY `uq_project_decline_reason_company_reason` (`company_id`,`reason`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `project_document` (
  `project_document_id` int unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(200) COLLATE utf8mb4_general_ci NOT NULL,
  `needs_estimate_to_move_on` bit(1) NOT NULL DEFAULT b'0',
  `needs_client_approval_to_move_on` bit(1) NOT NULL DEFAULT b'0',
  `can_expire` bit(1) NOT NULL DEFAULT b'0',
  `expire_days` smallint unsigned DEFAULT NULL,
  `next_project_document_id` int unsigned DEFAULT NULL,
  `should_be_worked` bit(1) NOT NULL DEFAULT b'0',
  `needs_to_be_contacted_by_lead_qualifier` bit(1) NOT NULL DEFAULT b'0',
  `represents_billable_sale_when_closed` bit(1) NOT NULL DEFAULT b'0',
  `declined` bit(1) NOT NULL DEFAULT b'0',
  `closed_by_default` bit(1) NOT NULL DEFAULT b'0',
  `declined_project_document_id` int unsigned DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `sort` tinyint unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`project_document_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `project_document_history` (
  `project_document_history_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `project_id` int unsigned NOT NULL,
  `project_document_id` int unsigned NOT NULL,
  `changed_by_employee_id` int unsigned DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`project_document_history_id`),
  KEY `idx_pdh_company_project_document` (`company_id`,`project_document_id`),
  KEY `idx_pdh_project` (`project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `project_image` (
  `project_image_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `project_id` int unsigned NOT NULL,
  `original_image` mediumblob NOT NULL,
  `display_image` mediumblob,
  `description` text COLLATE utf8mb4_general_ci NOT NULL,
  `visible_to_client` bit(1) NOT NULL DEFAULT b'0',
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`project_image_id`),
  KEY `idx_project_image_project` (`project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `project_line_item` (
  `project_line_item_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `project_id` int unsigned NOT NULL,
  `title` varchar(200) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `work_details` text COLLATE utf8mb4_general_ci,
  `item_type_id` int unsigned DEFAULT NULL,
  `line_item_template_id` int unsigned DEFAULT NULL,
  `estimated_hours` int unsigned NOT NULL,
  `taxable` bit(1) NOT NULL DEFAULT b'0',
  `client_optional` bit(1) NOT NULL DEFAULT b'0',
  `client_declined` bit(1) NOT NULL DEFAULT b'0',
  `quantity` decimal(10,2) NOT NULL,
  `price` decimal(10,2) NOT NULL,
  `discount_rate` decimal(5,4) DEFAULT NULL,
  `discount` decimal(10,2) DEFAULT NULL,
  `sort` int unsigned NOT NULL,
  `done_at` datetime DEFAULT NULL,
  `done_by_employee_id` int unsigned DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `arbostar_line_item_id` int unsigned DEFAULT NULL,
  PRIMARY KEY (`project_line_item_id`),
  UNIQUE KEY `uq_project_line_item_company_arbostar_line_item_id` (`company_id`,`arbostar_line_item_id`),
  KEY `idx_pli_project` (`project_id`),
  KEY `idx_pli_item_type` (`item_type_id`),
  KEY `idx_pli_line_item_template` (`line_item_template_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `project_line_item_image` (
  `project_line_item_image_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `project_image_id` int unsigned NOT NULL,
  `project_line_item_id` int unsigned NOT NULL,
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`project_line_item_image_id`),
  UNIQUE KEY `uq_plii_project_image_project_line_item` (`project_image_id`,`project_line_item_id`),
  KEY `idx_plii_line_item` (`project_line_item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `project_line_item_work_skill` (
  `project_line_item_work_skill_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `project_line_item_id` int unsigned NOT NULL,
  `work_skill_id` int unsigned NOT NULL,
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`project_line_item_work_skill_id`),
  UNIQUE KEY `uq_pliws_project_line_item_work_skill` (`project_line_item_id`,`work_skill_id`),
  KEY `idx_pliws_work_skill` (`work_skill_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `project_number` (
  `project_number_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `next_number` int unsigned NOT NULL DEFAULT '1',
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`project_number_id`),
  UNIQUE KEY `uq_project_number_company` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `software_role` (
  `software_role_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `name` varchar(100) COLLATE utf8mb4_general_ci NOT NULL,
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`software_role_id`),
  KEY `idx_software_role_company` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `software_role_permission` (
  `company_id` int unsigned NOT NULL,
  `software_role_id` int unsigned NOT NULL,
  `permission_id` int unsigned NOT NULL,
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`software_role_id`,`permission_id`),
  KEY `idx_srp_company_permission` (`company_id`,`permission_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `tax_rate` (
  `tax_rate_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `name` varchar(200) COLLATE utf8mb4_general_ci NOT NULL,
  `tax_rate` decimal(4,4) NOT NULL,
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`tax_rate_id`),
  UNIQUE KEY `uq_tax_rate_company_name` (`company_id`,`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `time_entry` (
  `time_entry_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `employee_id` int unsigned NOT NULL,
  `project_id` int unsigned NOT NULL,
  `work_date` date NOT NULL,
  `clock_in` datetime NOT NULL,
  `clock_out` datetime DEFAULT NULL,
  `regular_hours` decimal(5,2) NOT NULL DEFAULT '0.00',
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`time_entry_id`),
  KEY `idx_time_entry_company_work_date` (`company_id`,`work_date`),
  KEY `idx_time_entry_employee_work_date` (`employee_id`,`work_date`),
  KEY `idx_time_entry_project` (`project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `work_skill` (
  `work_skill_id` int unsigned NOT NULL AUTO_INCREMENT,
  `company_id` int unsigned NOT NULL,
  `name` varchar(100) COLLATE utf8mb4_general_ci NOT NULL,
  `hourly_rate` decimal(10,2) NOT NULL,
  `created_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  `updated_at` datetime NOT NULL DEFAULT (utc_timestamp()),
  PRIMARY KEY (`work_skill_id`),
  KEY `idx_work_skill_company` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
