// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

export const client = {
	company_id: 'company_id',
	name: 'name',
	is_commercial: 'is_commercial',
	primary_client_address_id: 'primary_client_address_id',
	billing_client_address_id: 'billing_client_address_id',
	primary_phone: 'primary_phone',
	primary_email: 'primary_email',
	tax_rate_id: 'tax_rate_id',
	notes: 'notes',
	referred_by: 'referred_by',
	arbostar_client_id: 'arbostar_client_id',
} as const

export const client_address = {
	company_id: 'company_id',
	client_id: 'client_id',
	name: 'name',
	address_line_1: 'address_line_1',
	address_line_2: 'address_line_2',
	city: 'city',
	state: 'state',
	zip: 'zip',
	contact: 'contact',
	phone: 'phone',
	email: 'email',
	latitude: 'latitude',
	longitude: 'longitude',
} as const

export const client_client_tag = {
	company_id: 'company_id',
	client_id: 'client_id',
	client_tag_id: 'client_tag_id',
	created_by_employee_id: 'created_by_employee_id',
} as const

export const client_contact = {
	company_id: 'company_id',
	client_id: 'client_id',
	description: 'description',
	name: 'name',
	phone: 'phone',
	email: 'email',
	arbostar_email_data: 'arbostar_email_data',
	is_primary: 'is_primary',
	sort_order: 'sort_order',
	arbostar_contact_id: 'arbostar_contact_id',
} as const

export const client_credit = {
	company_id: 'company_id',
	client_id: 'client_id',
	amount: 'amount',
	notes: 'notes',
	created_by_employee_id: 'created_by_employee_id',
} as const

export const client_tag = {
	company_id: 'company_id',
	name: 'name',
	color: 'color',
} as const

export const clock_session = {
	company_id: 'company_id',
	project_id: 'project_id',
	crew_id: 'crew_id',
	work_date: 'work_date',
	supersedes_clock_session_id: 'supersedes_clock_session_id',
	notes: 'notes',
	opened_by_employee_id: 'opened_by_employee_id',
} as const

export const clock_session_employee = {
	company_id: 'company_id',
	clock_session_id: 'clock_session_id',
	employee_id: 'employee_id',
	clock_in: 'clock_in',
	clock_in_day: 'clock_in_day',
	clock_out: 'clock_out',
	clocked_in_by_employee_id: 'clocked_in_by_employee_id',
	clocked_out_by_employee_id: 'clocked_out_by_employee_id',
} as const

export const clock_session_employee_history = {
	company_id: 'company_id',
	clock_session_employee_id: 'clock_session_employee_id',
	previous_clock_in: 'previous_clock_in',
	previous_clock_out: 'previous_clock_out',
	new_clock_in: 'new_clock_in',
	new_clock_out: 'new_clock_out',
	changed_by_employee_id: 'changed_by_employee_id',
} as const

export const clock_session_line_item = {
	company_id: 'company_id',
	clock_session_id: 'clock_session_id',
	project_line_item_id: 'project_line_item_id',
} as const

export const company = {
	name: 'name',
	logo: 'logo',
	brand_color: 'brand_color',
	default_crew_start_time: 'default_crew_start_time',
	invoice_due_after_days: 'invoice_due_after_days',
	timezone: 'timezone',
} as const

export const crew = {
	company_id: 'company_id',
	name: 'name',
	color: 'color',
} as const

export const crew_regular = {
	company_id: 'company_id',
	crew_id: 'crew_id',
	employee_id: 'employee_id',
} as const

export const crew_regular_history = {
	company_id: 'company_id',
	crew_id: 'crew_id',
	employee_id: 'employee_id',
	action: 'action',
	changed_by_employee_id: 'changed_by_employee_id',
} as const

export const employee = {
	company_id: 'company_id',
	name: 'name',
	email: 'email',
	login_name: 'login_name',
	phone: 'phone',
	password_hash: 'password_hash',
	is_owner: 'is_owner',
	number_of_password_hash_iterations: 'number_of_password_hash_iterations',
	arbostar_user_id: 'arbostar_user_id',
	default_crew_id: 'default_crew_id',
} as const

export const employee_session = {
	employee_id: 'employee_id',
	identifier: 'identifier',
	invalidated: 'invalidated',
	sign_in_user_agent: 'sign_in_user_agent',
	signed_in_at: 'signed_in_at',
	last_seen_user_agent: 'last_seen_user_agent',
	last_seen_at: 'last_seen_at',
} as const

export const employee_software_role = {
	company_id: 'company_id',
	employee_id: 'employee_id',
	software_role_id: 'software_role_id',
} as const

export const employee_work_skill = {
	company_id: 'company_id',
	employee_id: 'employee_id',
	work_skill_id: 'work_skill_id',
} as const

export const estimate_availability = {
	company_id: 'company_id',
	project_id: 'project_id',
	availability_date: 'availability_date',
	start_time: 'start_time',
	end_time: 'end_time',
} as const

export const invoice = {
	company_id: 'company_id',
	invoice_number: 'invoice_number',
	client_id: 'client_id',
	project_id: 'project_id',
	billing_name: 'billing_name',
	billing_address_line_1: 'billing_address_line_1',
	billing_address_line_2: 'billing_address_line_2',
	billing_city: 'billing_city',
	billing_state: 'billing_state',
	billing_zip: 'billing_zip',
	invoice_date: 'invoice_date',
	due_date: 'due_date',
	taxable: 'taxable',
	tax_rate_id: 'tax_rate_id',
	tax_rate: 'tax_rate',
	subtotal: 'subtotal',
	taxable_subtotal: 'taxable_subtotal',
	discount_rate: 'discount_rate',
	discount: 'discount',
	discount_description: 'discount_description',
	line_item_discount_subtotal: 'line_item_discount_subtotal',
	client_credit_applied: 'client_credit_applied',
	tax_total: 'tax_total',
	fee: 'fee',
	total: 'total',
	created_by_employee_id: 'created_by_employee_id',
	arbostar_invoice_id: 'arbostar_invoice_id',
} as const

export const invoice_line_item = {
	company_id: 'company_id',
	invoice_id: 'invoice_id',
	project_line_item_id: 'project_line_item_id',
	description: 'description',
	quantity: 'quantity',
	price: 'price',
	discount_rate: 'discount_rate',
	discount: 'discount',
	discount_description: 'discount_description',
	taxable: 'taxable',
	sort: 'sort',
} as const

export const invoice_number = {
	company_id: 'company_id',
	next_number: 'next_number',
} as const

export const item_type = {
	company_id: 'company_id',
	name: 'name',
	taxable: 'taxable',
} as const

export const line_item_template = {
	company_id: 'company_id',
	title: 'title',
	estimated_hours: 'estimated_hours',
	price: 'price',
	arbostar_work_type_id: 'arbostar_work_type_id',
} as const

export const line_item_template_work_skill = {
	company_id: 'company_id',
	line_item_template_id: 'line_item_template_id',
	work_skill_id: 'work_skill_id',
} as const

export const migration = {
	migration_number: 'migration_number',
	ran_at: 'ran_at',
} as const

export const payment = {
	company_id: 'company_id',
	client_id: 'client_id',
	project_id: 'project_id',
	amount: 'amount',
	tip: 'tip',
	merchant_fee: 'merchant_fee',
	pay_date: 'pay_date',
	payment_method_id: 'payment_method_id',
	notes: 'notes',
	recorded_by_employee_id: 'recorded_by_employee_id',
	arbostar_payment_id: 'arbostar_payment_id',
} as const

export const payment_invoice = {
	company_id: 'company_id',
	payment_id: 'payment_id',
	invoice_id: 'invoice_id',
	amount: 'amount',
} as const

export const payment_method = {
	company_id: 'company_id',
	name: 'name',
} as const

export const permission = {
	code: 'code',
	name: 'name',
} as const

export const project = {
	company_id: 'company_id',
	project_document_id: 'project_document_id',
	number: 'number',
	client_id: 'client_id',
	client_address_id: 'client_address_id',
	address_line_1: 'address_line_1',
	address_line_2: 'address_line_2',
	city: 'city',
	state: 'state',
	zip: 'zip',
	due_date: 'due_date',
	emergency: 'emergency',
	assigned_estimator_employee_id: 'assigned_estimator_employee_id',
	lead_details: 'lead_details',
	created_by_employee_id: 'created_by_employee_id',
	needs_client_approval: 'needs_client_approval',
	sent_for_client_approval: 'sent_for_client_approval',
	taxable: 'taxable',
	tax_rate_id: 'tax_rate_id',
	tax_rate: 'tax_rate',
	subtotal: 'subtotal',
	taxable_subtotal: 'taxable_subtotal',
	discount_rate: 'discount_rate',
	discount: 'discount',
	discount_description: 'discount_description',
	line_item_discount_subtotal: 'line_item_discount_subtotal',
	tax_total: 'tax_total',
	total: 'total',
	notes_for_crew: 'notes_for_crew',
	notes_for_office: 'notes_for_office',
	closed: 'closed',
	closed_at: 'closed_at',
	closed_date: 'closed_date',
	project_decline_reason_id: 'project_decline_reason_id',
	lead_source: 'lead_source',
	contact_name: 'contact_name',
	contact_phone: 'contact_phone',
	contact_email: 'contact_email',
	latitude: 'latitude',
	longitude: 'longitude',
} as const

export const project_client_approval = {
	company_id: 'company_id',
	project_id: 'project_id',
	customer_signature: 'customer_signature',
	verbal_approval: 'verbal_approval',
	added_by_employee_id: 'added_by_employee_id',
} as const

export const project_crew = {
	company_id: 'company_id',
	project_id: 'project_id',
	crew_id: 'crew_id',
	work_date: 'work_date',
	day_order: 'day_order',
	start_time: 'start_time',
} as const

export const project_crew_employee = {
	company_id: 'company_id',
	project_crew_id: 'project_crew_id',
	employee_id: 'employee_id',
} as const

export const project_crew_project_line_item = {
	company_id: 'company_id',
	project_crew_id: 'project_crew_id',
	project_line_item_id: 'project_line_item_id',
} as const

export const project_decline_reason = {
	company_id: 'company_id',
	reason: 'reason',
} as const

export const project_document = {
	name: 'name',
	needs_estimate_to_move_on: 'needs_estimate_to_move_on',
	needs_client_approval_to_move_on: 'needs_client_approval_to_move_on',
	can_expire: 'can_expire',
	expire_days: 'expire_days',
	next_project_document_id: 'next_project_document_id',
	should_be_worked: 'should_be_worked',
	needs_to_be_contacted_by_lead_qualifier: 'needs_to_be_contacted_by_lead_qualifier',
	represents_billable_sale_when_closed: 'represents_billable_sale_when_closed',
	declined: 'declined',
	closed_by_default: 'closed_by_default',
	declined_project_document_id: 'declined_project_document_id',
	sort: 'sort',
} as const

export const project_document_history = {
	company_id: 'company_id',
	project_id: 'project_id',
	project_document_id: 'project_document_id',
	changed_by_employee_id: 'changed_by_employee_id',
} as const

export const project_image = {
	company_id: 'company_id',
	project_id: 'project_id',
	original_image: 'original_image',
	display_image: 'display_image',
	description: 'description',
	visible_to_client: 'visible_to_client',
} as const

export const project_line_item = {
	company_id: 'company_id',
	project_id: 'project_id',
	title: 'title',
	work_details: 'work_details',
	item_type_id: 'item_type_id',
	line_item_template_id: 'line_item_template_id',
	estimated_hours: 'estimated_hours',
	taxable: 'taxable',
	client_optional: 'client_optional',
	client_declined: 'client_declined',
	quantity: 'quantity',
	price: 'price',
	discount_rate: 'discount_rate',
	discount: 'discount',
	discount_description: 'discount_description',
	sort: 'sort',
	done_at: 'done_at',
	done_by_employee_id: 'done_by_employee_id',
	arbostar_line_item_id: 'arbostar_line_item_id',
} as const

export const project_line_item_image = {
	company_id: 'company_id',
	project_image_id: 'project_image_id',
	project_line_item_id: 'project_line_item_id',
} as const

export const project_line_item_work_skill = {
	company_id: 'company_id',
	project_line_item_id: 'project_line_item_id',
	work_skill_id: 'work_skill_id',
} as const

export const project_number = {
	company_id: 'company_id',
	next_number: 'next_number',
} as const

export const software_role = {
	company_id: 'company_id',
	name: 'name',
} as const

export const software_role_permission = {
	company_id: 'company_id',
	software_role_id: 'software_role_id',
	permission_id: 'permission_id',
} as const

export const tax_rate = {
	company_id: 'company_id',
	name: 'name',
	tax_rate: 'tax_rate',
} as const

export const work_skill = {
	company_id: 'company_id',
	name: 'name',
	hourly_rate: 'hourly_rate',
} as const
