// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

// Columns whose DATA_TYPE is mediumblob or longblob: client queries must never select them.
export const large_blob_columns = {
	project_image: ['original_image', 'display_image', 'thumbnail_image'],
} as const
