// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

// Tables with a unique key (or primary key) on company_id alone: each company owns at most one row.
export const tables_unique_on_company_id = {
	company: 'company',
	invoice_number: 'invoice_number',
	project_number: 'project_number',
} as const
