// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.

export type Schema = {
	client: DbClient
	client_address: DbClientAddress
	client_contact: DbClientContact
	company: DbCompany
	crew: DbCrew
	crew_member: DbCrewMember
	employee: DbEmployee
	employee_session: DbEmployeeSession
	employee_software_role: DbEmployeeSoftwareRole
	estimate_availability: DbEstimateAvailability
	item_type: DbItemType
	migration: DbMigration
	payment: DbPayment
	payment_method: DbPaymentMethod
	payment_project: DbPaymentProject
	permission: DbPermission
	project: DbProject
	project_client_approval: DbProjectClientApproval
	project_decline_reason: DbProjectDeclineReason
	project_document: DbProjectDocument
	project_line_item: DbProjectLineItem
	project_line_item_image: DbProjectLineItemImage
	project_number: DbProjectNumber
	project_work_skill: DbProjectWorkSkill
	software_role: DbSoftwareRole
	software_role_permission: DbSoftwareRolePermission
	tax_rate: DbTaxRate
	time_entry: DbTimeEntry
	work_skill: DbWorkSkill
}

export type InsertableSchema = {
	client: DbInsertableClient
	client_address: DbInsertableClientAddress
	client_contact: DbInsertableClientContact
	company: DbInsertableCompany
	crew: DbInsertableCrew
	crew_member: DbInsertableCrewMember
	employee: DbInsertableEmployee
	employee_session: DbInsertableEmployeeSession
	employee_software_role: DbInsertableEmployeeSoftwareRole
	estimate_availability: DbInsertableEstimateAvailability
	item_type: DbInsertableItemType
	migration: DbInsertableMigration
	payment: DbInsertablePayment
	payment_method: DbInsertablePaymentMethod
	payment_project: DbInsertablePaymentProject
	permission: DbInsertablePermission
	project: DbInsertableProject
	project_client_approval: DbInsertableProjectClientApproval
	project_decline_reason: DbInsertableProjectDeclineReason
	project_document: DbInsertableProjectDocument
	project_line_item: DbInsertableProjectLineItem
	project_line_item_image: DbInsertableProjectLineItemImage
	project_number: DbInsertableProjectNumber
	project_work_skill: DbInsertableProjectWorkSkill
	software_role: DbInsertableSoftwareRole
	software_role_permission: DbInsertableSoftwareRolePermission
	tax_rate: DbInsertableTaxRate
	time_entry: DbInsertableTimeEntry
	work_skill: DbInsertableWorkSkill
}
