// Dumps one company's rows from every table that has a company_id column into
// company_inserts.sql at the repo root (gitignored — it holds client data). The file
// deletes the company's rows per table and re-inserts them, capped at 100 rows per
// INSERT. Run with the same env vars as the other db scripts:
//
//   pnpm exec dotenv -- node scripts/dump_company_inserts.ts --company_id 9

import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parseArgs } from 'node:util'
import mysql from 'mysql2/promise'
import assert from '#shared/assert.ts'
import { chunk, filter, for_each, map } from '#shared/array.ts'

function requireEnv(key: string): string {
	const val = process.env[key]
	if (val === undefined) throw new Error(`Missing env var: ${key}`)
	return val
}

const { values: args } = parseArgs({ options: { company_id: { type: 'string' } } })
assert(
	args.company_id !== undefined && /^\d+$/.test(args.company_id),
	'Usage: node scripts/dump_company_inserts.ts --company_id <id>',
)
const company_id = args.company_id

const ROWS_PER_INSERT = 100
const BINARY_TYPES = new Set(['binary', 'varbinary', 'blob', 'tinyblob', 'mediumblob', 'longblob'])
const OUTPUT_PATH = join(dirname(fileURLToPath(import.meta.url)), '..', 'company_inserts.sql')

const connection = await mysql.createConnection({
	host: requireEnv('MYSQL_HOST'),
	port: Number(requireEnv('MYSQL_PORT')),
	user: requireEnv('MYSQL_USER'),
	password: requireEnv('MYSQL_PASS'),
	database: requireEnv('MYSQL_DB'),
	typeCast: field => (field.type === 'JSON' ? field.string('utf8') : field.string()),
})

try {
	await connection.query(`SET time_zone = '+00:00'`)

	const [column_rows] = (await connection.query(`
		SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, EXTRA
		FROM information_schema.COLUMNS
		WHERE TABLE_SCHEMA = DATABASE()
		ORDER BY TABLE_NAME, ORDINAL_POSITION
	`)) as unknown as [Array<{ TABLE_NAME: string; COLUMN_NAME: string; DATA_TYPE: string; EXTRA: string }>]

	type Column = { name: string; data_type: string }
	const columns_by_table = new Map<string, Column[]>()
	for_each(
		filter(column_rows, row => !row.EXTRA.includes('GENERATED')),
		row => {
			const columns = columns_by_table.get(row.TABLE_NAME) ?? []
			columns.push({ name: row.COLUMN_NAME, data_type: row.DATA_TYPE })
			columns_by_table.set(row.TABLE_NAME, columns)
		},
	)

	const tables = filter(
		[...columns_by_table.keys()],
		table => columns_by_table.get(table)!.some(column => column.name === 'company_id'),
	)

	const lines: string[] = [
		`-- Rows for company ${company_id}, every table with a company_id column.`,
		`-- Generated by scripts/dump_company_inserts.ts. Holds client data — never commit.`,
		`SET @OLD_TIME_ZONE=@@TIME_ZONE;`,
		`SET TIME_ZONE='+00:00';`,
		`SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;`,
		`SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;`,
		``,
	]

	for (const table of tables) {
		const columns = columns_by_table.get(table)!
		const select_expressions = map(columns, column => {
			if (BINARY_TYPES.has(column.data_type)) return `HEX(\`${column.name}\`) AS \`${column.name}\``
			if (column.data_type === 'bit') return `\`${column.name}\` + 0 AS \`${column.name}\``
			return `\`${column.name}\``
		})
		const [rows] = (await connection.query({
			sql: `SELECT ${select_expressions.join(', ')} FROM \`${table}\` WHERE company_id = ? ORDER BY 1`,
			values: [company_id],
			rowsAsArray: true,
		})) as unknown as [Array<Array<string | null>>]

		lines.push(`-- ${rows.length} rows for table \`${table}\``)
		lines.push(`DELETE FROM \`${table}\` WHERE company_id = ${company_id};`)
		for (const rows_chunk of chunk(rows, ROWS_PER_INSERT)) {
			const column_list = map(columns, column => `\`${column.name}\``).join(', ')
			const value_rows = map(rows_chunk, row =>
				`(${map(row, (value, index) => {
					if (value === null) return 'NULL'
					const column = columns[index]!
					if (BINARY_TYPES.has(column.data_type)) return `X'${value}'`
					if (column.data_type === 'bit') return value
					return connection.escape(value)
				}).join(',')})`,
			)
			lines.push(`INSERT INTO \`${table}\` (${column_list}) VALUES\n${value_rows.join(',\n')};`)
		}
		lines.push(``)
		console.log(`  ${table}: ${rows.length} rows`)
	}

	lines.push(`SET TIME_ZONE=@OLD_TIME_ZONE;`)
	lines.push(`SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;`)
	lines.push(`SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;`)
	lines.push(``)

	writeFileSync(OUTPUT_PATH, lines.join('\n'))
	console.log(`Wrote ${tables.length} tables -> ${OUTPUT_PATH}`)
} finally {
	await connection.end()
}
