import { for_each, map, filter } from '#shared/array.ts'
import { createConnection } from 'mysql2/promise'
import type { RowDataPacket } from 'mysql2'
import { writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import assert from '#shared/assert.ts'

const __dirname = dirname(fileURLToPath(import.meta.url))
const PROJECT_ROOT = join(__dirname, '..')
const SCHEMA_DIR = join(PROJECT_ROOT, 'schema')
const TYPE_DIR = join(SCHEMA_DIR, 'type')
const AUTOGENERATED_DIR = join(TYPE_DIR, 'autogenerated')

const NON_INSERTABLE_COLUMNS = new Set(['created_at', 'updated_at'])

const AUTOGENERATED_NOTE = '// AUTO-GENERATED by scripts/export_schema.ts — do not edit by hand.'

const MYSQL_TYPE_TO_TS: Record<string, (col: ColumnMeta) => string> = {
	int: () => 'bigint',
	smallint: () => 'bigint',
	decimal: () => 'FinancialNumber',
	bit: () => 'boolean',
	tinyint: () => 'boolean',
	datetime: () => 'Temporal.Instant',
	date: () => 'Temporal.PlainDate',
	time: () => 'Temporal.PlainTime',
	varchar: () => 'string',
	json: () => 'string',
	char: () => 'string',
	text: () => 'string',
	blob: () => 'Buffer',
	binary: () => 'Buffer',
}

type ColumnMeta = RowDataPacket & {
	TABLE_NAME: string
	COLUMN_NAME: string
	DATA_TYPE: string
	IS_NULLABLE: string
	EXTRA: string
}

function toPascalCase(snake: string): string {
	return map(snake.split('_'), s => s[0]!.toUpperCase() + s.slice(1)).join('')
}

function columnTsType(col: ColumnMeta): string {
	const mapFn = MYSQL_TYPE_TO_TS[col.DATA_TYPE]
	assert(mapFn, `Every type must exist in MYSQL_TYPE_TO_TS: "${col.DATA_TYPE}"`)
	const base = mapFn(col)
	return col.IS_NULLABLE === 'YES' ? `${base} | null` : base
}

function isInsertable(col: ColumnMeta): boolean {
	return !NON_INSERTABLE_COLUMNS.has(col.COLUMN_NAME) && !col.EXTRA.includes('auto_increment')
}

function typeFields(cols: ColumnMeta[], predicate?: (col: ColumnMeta) => boolean, indent = '\t'): string {
	const filtered = predicate ? filter(cols, predicate) : cols
	return map(filtered, col => `${indent}${col.COLUMN_NAME}: ${columnTsType(col)}`).join('\n')
}

function generateAutogeneratedFile(table: string, cols: ColumnMeta[]): string {
	const pascal = toPascalCase(table)
	return `${AUTOGENERATED_NOTE}

import type { Temporal } from '@js-temporal/polyfill'
import type { FinancialNumber } from 'financial-number'

export type AutogeneratedInsertable${pascal} = {
${typeFields(cols, isInsertable)}
}

export type Autogenerated${pascal} = {
${typeFields(cols)}
}
`
}

function generateTypeFile(table: string): string {
	const pascal = toPascalCase(table)
	return `import type { AutogeneratedInsertable${pascal}, Autogenerated${pascal} } from './autogenerated/autogenerated_${table}.d.ts'

declare global {
\ttype DbInsertable${pascal} = AutogeneratedInsertable${pascal}
\ttype Db${pascal} = Autogenerated${pascal}
}
`
}

function generateTypesFile(tables: Map<string, ColumnMeta[]>): string {
	const entries = map([...tables.keys()], table => `\t${table}: Db${toPascalCase(table)}`).join('\n')
	const insertableEntries = map([...tables.keys()], table => `\t${table}: DbInsertable${toPascalCase(table)}`).join('\n')
	return `${AUTOGENERATED_NOTE}\n\nexport type Schema = {\n${entries}\n}\n\nexport type InsertableSchema = {\n${insertableEntries}\n}\n`
}

function generateColumnNamesFile(
	tables: Map<string, ColumnMeta[]>,
	predicate?: (col: ColumnMeta) => boolean,
): string {
	const tableExports = map([...tables.entries()], ([table, cols]) => {
		const filtered = predicate ? filter(cols, predicate) : cols
		const colEntries = map(filtered, col => `\t${col.COLUMN_NAME}: '${col.COLUMN_NAME}'`).join(',\n')
		return `export const ${table} = {\n${colEntries},\n} as const`
	}).join('\n\n')
	return `${AUTOGENERATED_NOTE}\n\n${tableExports}\n`
}

function requireEnv(key: string): string {
	const val = process.env[key]
	if (val === undefined) throw new Error(`Missing env var: ${key}`)
	return val
}

const conn = await createConnection({
	host: requireEnv('MYSQL_HOST'),
	port: Number(requireEnv('MYSQL_PORT')),
	user: requireEnv('MYSQL_USER'),
	password: requireEnv('MYSQL_PASS'),
	database: requireEnv('MYSQL_DB'),
	// In prod, MYSQL_CA_CERT (base64-encoded PEM) is set, which makes TLS required and
	// verifies the server against the CA. Unset locally, so the connection is plaintext.
	...(process.env.MYSQL_CA_CERT
		? { ssl: { ca: Buffer.from(process.env.MYSQL_CA_CERT, 'base64').toString('utf8') } }
		: {}),
})

const [rows] = await conn.query<ColumnMeta[]>(`
	SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, EXTRA
	FROM information_schema.COLUMNS
	WHERE TABLE_SCHEMA = DATABASE()
	ORDER BY TABLE_NAME, ORDINAL_POSITION
`)

await conn.end()

const tables = new Map<string, ColumnMeta[]>()
for_each(rows, col => {
	if (!tables.has(col.TABLE_NAME)) tables.set(col.TABLE_NAME, [])
	tables.get(col.TABLE_NAME)!.push(col)
})

mkdirSync(AUTOGENERATED_DIR, { recursive: true })

for (const [table, cols] of tables) {
	const autogeneratedPath = join(AUTOGENERATED_DIR, `autogenerated_${table}.d.ts`)
	writeFileSync(autogeneratedPath, generateAutogeneratedFile(table, cols))
	console.log(`wrote ${autogeneratedPath}`)

	const typePath = join(TYPE_DIR, `${table}.d.ts`)
	if (existsSync(typePath)) {
		console.log(`skipped ${typePath} (already exists)`)
	} else {
		writeFileSync(typePath, generateTypeFile(table))
		console.log(`wrote ${typePath}`)
	}
}

const allColumnNamesPath = join(SCHEMA_DIR, 'all_table_column_names.ts')
writeFileSync(allColumnNamesPath, generateColumnNamesFile(tables))
console.log(`wrote ${allColumnNamesPath}`)

const insertableColumnNamesPath = join(SCHEMA_DIR, 'insertable_table_column_names.ts')
writeFileSync(insertableColumnNamesPath, generateColumnNamesFile(tables, isInsertable))
console.log(`wrote ${insertableColumnNamesPath}`)

const typesPath = join(SCHEMA_DIR, 'types.ts')
writeFileSync(typesPath, generateTypesFile(tables))
console.log(`wrote ${typesPath}`)
