import ts from 'typescript'
import { readdirSync, writeFileSync, mkdirSync } from 'node:fs'
import { resolve, join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const PROJECT_ROOT = resolve(__dirname, '..')

const configPath = resolve(PROJECT_ROOT, 'tsconfig.json')
const configFile = ts.readConfigFile(configPath, ts.sys.readFile)
const parsed = ts.parseJsonConfigFileContent(configFile.config, ts.sys, PROJECT_ROOT)

const fnDir = join(PROJECT_ROOT, 'worker', 'server_functions')
const fnFiles = readdirSync(fnDir)
	.filter(f => f.endsWith('.fns.ts'))
	.map(f => join(fnDir, f))

const program = ts.createProgram(
	[...new Set([...parsed.fileNames, ...fnFiles])],
	parsed.options,
)
const checker = program.getTypeChecker()

const type_to_string_flags =
	ts.TypeFormatFlags.NoTruncation |
	ts.TypeFormatFlags.UseAliasDefinedOutsideCurrentScope

// The `Autogenerated*` types live behind import-only declarations that the client can't resolve.
// Each has a global `Db*` alias (e.g. `type DbCompany = AutogeneratedCompany`), so rewrite to that.
const to_client_type = (type_string: string) => type_string.replace(/\bAutogenerated(\w+)\b/g, 'Db$1')

const resolves_to_any = (type: ts.Type) => (type.flags & ts.TypeFlags.Any) !== 0

type FnEntry = { arg: string; returns: string }
const allFunctions = new Map<string, FnEntry>()
const problems: string[] = []

for (const filePath of fnFiles) {
	const sf = program.getSourceFile(filePath)
	if (!sf) {
		console.error(`could not load ${filePath}`)
		continue
	}

	function visit(node: ts.Node): void {
		if (
			ts.isVariableDeclaration(node) &&
			ts.isIdentifier(node.name) &&
			node.name.text === 'functions' &&
			node.initializer
		) {
			const source = ts.isCallExpression(node.initializer) && node.initializer.arguments[0]
				? node.initializer.arguments[0]
				: node.initializer
			const functionsType = checker.getTypeAtLocation(source)
			for (const prop of checker.getPropertiesOfType(functionsType)) {
				const propType = checker.getTypeOfSymbol(prop)

				const validatorProp = propType.getProperty('validator')
				if (!validatorProp) continue
				const isValidProp = checker.getTypeOfSymbol(validatorProp).getProperty('is_valid')
				if (!isValidProp) continue
				const isValidSig = checker.getSignaturesOfType(
					checker.getTypeOfSymbol(isValidProp),
					ts.SignatureKind.Call,
				)[0]
				if (!isValidSig) continue
				const predicate = checker.getTypePredicateOfSignature(isValidSig)
				if (!predicate?.type) continue
				if (resolves_to_any(predicate.type)) problems.push(`${prop.name}: argument type resolves to \`any\``)
				const argType = to_client_type(checker.typeToString(predicate.type, undefined, type_to_string_flags))

				const fnProp = propType.getProperty('fn')
				if (!fnProp) continue
				const fnSig = checker.getSignaturesOfType(
					checker.getTypeOfSymbol(fnProp),
					ts.SignatureKind.Call,
				)[0]
				if (!fnSig) continue
				const rawReturn = checker.getReturnTypeOfSignature(fnSig)
				const typeArgs = checker.getTypeArguments(rawReturn as ts.TypeReference)
				const returnElement = typeArgs[0] ?? rawReturn
				if (resolves_to_any(returnElement)) problems.push(`${prop.name}: return type resolves to \`any\``)
				const returnType = to_client_type(checker.typeToString(returnElement, undefined, type_to_string_flags))

				allFunctions.set(prop.name, { arg: argType, returns: returnType })
			}
		}
		ts.forEachChild(node, visit)
	}
	visit(sf)
}

if (problems.length) {
	console.error(`server function types resolve to \`any\`:\n${problems.map(p => `  - ${p}`).join('\n')}`)
	process.exit(1)
}

const type_entries = [...allFunctions.entries()]
	.map(([name, { arg, returns }]) => `\t${name}: (arg: ${arg}) => Promise<${returns}>`)
	.join('\n')

// Recursive validator types (e.g. SelectGrouping, AndOrGrouping) can't be inlined by the type
// printer, so they appear by name in the generated strings. Unlike the global Db* aliases they're
// module-scoped, so import whichever ones are actually referenced.
const validator_module_specifier = '#shared/sql_request/safe_sql_query_validator.ts'
const validator_source = program.getSourceFile(resolve(PROJECT_ROOT, 'shared', 'sql_request', 'safe_sql_query_validator.ts'))
const validator_module_symbol = validator_source && checker.getSymbolAtLocation(validator_source)
const referenced_validator_types = (validator_module_symbol ? checker.getExportsOfModule(validator_module_symbol) : [])
	.filter(symbol => symbol.flags & (ts.SymbolFlags.TypeAlias | ts.SymbolFlags.Interface))
	.map(symbol => symbol.name)
	.filter(name => new RegExp(`\\b${name}\\b`).test(type_entries))
	.sort()

const validator_import = referenced_validator_types.length
	? `import type { ${referenced_validator_types.join(', ')} } from '${validator_module_specifier}'\n`
	: ''

const call_entries = [...allFunctions.keys()]
	.map(name => `\t${name}: call_server_function('${name}'),`)
	.join('\n')

// A single `.ts` (not a `.d.ts`) so the normal type-checking step covers it — `skipLibCheck`
// skips declaration files, which would let an unresolved type silently degrade to `any`.
const outputPath = join(PROJECT_ROOT, 'client', 'lib', 'server_functions.ts')
mkdirSync(dirname(outputPath), { recursive: true })
writeFileSync(outputPath, `// AUTO-GENERATED by scripts/generate_server_function_types.ts — do not edit by hand.
import f3tch from '#shared/f3tch.ts'
${validator_import}
const call_server_function = (function_name: string) => async (arg: unknown) => f3tch(\`/api/fn/\${function_name}\`, {
	method: 'POST',
	body: arg,
})

const server_functions: {
${type_entries}
} = {
${call_entries}
}

export default server_functions
`)
console.log(`wrote ${outputPath}`)
