import ts from 'typescript'
import { readdirSync, writeFileSync, mkdirSync } from 'node:fs'
import { resolve, join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const PROJECT_ROOT = resolve(__dirname, '..')

const configPath = resolve(PROJECT_ROOT, 'tsconfig.json')
const configFile = ts.readConfigFile(configPath, ts.sys.readFile)
const parsed = ts.parseJsonConfigFileContent(configFile.config, ts.sys, PROJECT_ROOT)

const fnDir = join(PROJECT_ROOT, 'worker', 'server_functions')
const fnFiles = readdirSync(fnDir)
	.filter(f => f.endsWith('.fns.ts'))
	.map(f => join(fnDir, f))

const program = ts.createProgram(
	[...new Set([...parsed.fileNames, ...fnFiles])],
	parsed.options,
)
const checker = program.getTypeChecker()

const type_to_string_flags =
	ts.TypeFormatFlags.NoTruncation |
	ts.TypeFormatFlags.UseAliasDefinedOutsideCurrentScope

// The `Autogenerated*` types live behind import-only declarations that the client can't resolve.
// Each has a global `Db*` alias (e.g. `type DbCompany = AutogeneratedCompany`), so rewrite to that.
const to_client_type = (type_string: string) => type_string.replace(/\bAutogenerated(\w+)\b/g, 'Db$1')

const resolves_to_any = (type: ts.Type) => (type.flags & ts.TypeFlags.Any) !== 0

type FnEntry = { arg: string; returns: string }
const allFunctions = new Map<string, FnEntry>()
const problems: string[] = []

for (const filePath of fnFiles) {
	const sf = program.getSourceFile(filePath)
	if (!sf) {
		console.error(`could not load ${filePath}`)
		continue
	}

	function visit(node: ts.Node): void {
		if (
			ts.isVariableDeclaration(node) &&
			ts.isIdentifier(node.name) &&
			node.name.text === 'functions' &&
			node.initializer
		) {
			const functionsType = checker.getTypeAtLocation(node.initializer)
			for (const prop of checker.getPropertiesOfType(functionsType)) {
				const propType = checker.getTypeOfSymbol(prop)

				const validatorProp = propType.getProperty('validator')
				if (!validatorProp) continue
				const isValidProp = checker.getTypeOfSymbol(validatorProp).getProperty('is_valid')
				if (!isValidProp) continue
				const isValidSig = checker.getSignaturesOfType(
					checker.getTypeOfSymbol(isValidProp),
					ts.SignatureKind.Call,
				)[0]
				if (!isValidSig) continue
				const predicate = checker.getTypePredicateOfSignature(isValidSig)
				if (!predicate?.type) continue
				if (resolves_to_any(predicate.type)) problems.push(`${prop.name}: argument type resolves to \`any\``)
				const argType = to_client_type(checker.typeToString(predicate.type, undefined, type_to_string_flags))

				const fnProp = propType.getProperty('fn')
				if (!fnProp) continue
				const fnSig = checker.getSignaturesOfType(
					checker.getTypeOfSymbol(fnProp),
					ts.SignatureKind.Call,
				)[0]
				if (!fnSig) continue
				const rawReturn = checker.getReturnTypeOfSignature(fnSig)
				const typeArgs = checker.getTypeArguments(rawReturn as ts.TypeReference)
				const returnElement = typeArgs[0] ?? rawReturn
				if (resolves_to_any(returnElement)) problems.push(`${prop.name}: return type resolves to \`any\``)
				const returnType = to_client_type(checker.typeToString(returnElement, undefined, type_to_string_flags))

				allFunctions.set(prop.name, { arg: argType, returns: returnType })
			}
		}
		ts.forEachChild(node, visit)
	}
	visit(sf)
}

if (problems.length) {
	console.error(`server function types resolve to \`any\`:\n${problems.map(p => `  - ${p}`).join('\n')}`)
	process.exit(1)
}

const entries = [...allFunctions.entries()]
	.map(([name, { arg, returns }]) => `\t${name}: (arg: ${arg}) => Promise<${returns}>`)
	.join('\n')

const outputPath = join(PROJECT_ROOT, 'client', 'lib', 'server_functions.d.ts')
mkdirSync(dirname(outputPath), { recursive: true })
writeFileSync(outputPath, `declare const server_functions: {\n${entries}\n}\nexport default server_functions\n`)
console.log(`wrote ${outputPath}`)

// `skipLibCheck` (inherited by the client tsconfig) means tsc never checks the generated `.d.ts`,
// so an unresolved type (e.g. a module-scoped `Autogenerated*` instead of its global `Db*` alias)
// would silently become `any` at the call site. Re-check the file here with the schema globals in
// scope but `skipLibCheck` off, so any unresolved reference fails the build.
const validate_generated_declaration = (declaration_file: string) => {
	const schema_type_dir = join(PROJECT_ROOT, 'schema', 'type')
	const schema_globals = readdirSync(schema_type_dir, { recursive: true })
		.map(entry => join(schema_type_dir, entry.toString()))
		.filter(file => file.endsWith('.d.ts'))

	const validation_program = ts.createProgram(
		[declaration_file, ...schema_globals],
		{ ...parsed.options, skipLibCheck: false, noEmit: true, types: [] },
	)

	const declaration_diagnostics = ts.getPreEmitDiagnostics(validation_program)
		.filter(diagnostic => diagnostic.file && resolve(diagnostic.file.fileName) === resolve(declaration_file))

	if (declaration_diagnostics.length) {
		const host: ts.FormatDiagnosticsHost = {
			getCanonicalFileName: fileName => fileName,
			getCurrentDirectory: ts.sys.getCurrentDirectory,
			getNewLine: () => ts.sys.newLine,
		}
		console.error(`\n${declaration_file} does not type-check:\n`)
		console.error(ts.formatDiagnosticsWithColorAndContext(declaration_diagnostics, host))
		process.exit(1)
	}
}

validate_generated_declaration(outputPath)

const jsEntries = [...allFunctions.keys()]
	.map(name => `\t${name}: call_server_function('${name}'),`)
	.join('\n')

const jsOutputPath = join(PROJECT_ROOT, 'client', 'lib', 'server_functions.js')
writeFileSync(jsOutputPath, `import f3tch from '#shared/f3tch.ts'

const call_server_function = (function_name) => async (arg) => f3tch(\`/api/fn/\${function_name}\`, {
	method: 'POST',
	body: arg,
})

export default {
${jsEntries}
}
`)
console.log(`wrote ${jsOutputPath}`)
