import type { AutogeneratedInsertableClient, AutogeneratedClient } from './autogenerated/autogenerated_client.d.ts'

declare global {
	type DbInsertableClient = AutogeneratedInsertableClient
	type DbClient = AutogeneratedClient
}
