import type { AutogeneratedInsertableClientTag, AutogeneratedClientTag } from './autogenerated/autogenerated_client_tag.d.ts'

declare global {
	type DbInsertableClientTag = AutogeneratedInsertableClientTag
	type DbClientTag = AutogeneratedClientTag
}
