import type { AutogeneratedInsertableClientCredit, AutogeneratedClientCredit } from './autogenerated/autogenerated_client_credit.d.ts'

declare global {
	type DbInsertableClientCredit = AutogeneratedInsertableClientCredit
	type DbClientCredit = AutogeneratedClientCredit
}
