import type { AutogeneratedInsertableClientContact, AutogeneratedClientContact } from './autogenerated/autogenerated_client_contact.ts'

declare global {
	type DbInsertableClientContact = AutogeneratedInsertableClientContact
	type DbClientContact = AutogeneratedClientContact
}
