import type { AutogeneratedInsertableClientAddress, AutogeneratedClientAddress } from './autogenerated/autogenerated_client_address.ts'

declare global {
	type DbInsertableClientAddress = AutogeneratedInsertableClientAddress
	type DbClientAddress = AutogeneratedClientAddress
}
