import type { AutogeneratedInsertableClientClientTag, AutogeneratedClientClientTag } from './autogenerated/autogenerated_client_client_tag.d.ts'

declare global {
	type DbInsertableClientClientTag = AutogeneratedInsertableClientClientTag
	type DbClientClientTag = AutogeneratedClientClientTag
}
