import type { AutogeneratedInsertableClockSession, AutogeneratedClockSession } from './autogenerated/autogenerated_clock_session.d.ts'

declare global {
	type DbInsertableClockSession = AutogeneratedInsertableClockSession
	type DbClockSession = AutogeneratedClockSession
}
