import type { AutogeneratedInsertableClockSessionEmployee, AutogeneratedClockSessionEmployee } from './autogenerated/autogenerated_clock_session_employee.d.ts'

declare global {
	type DbInsertableClockSessionEmployee = AutogeneratedInsertableClockSessionEmployee
	type DbClockSessionEmployee = AutogeneratedClockSessionEmployee
}
