import type { AutogeneratedInsertableClockSessionLineItem, AutogeneratedClockSessionLineItem } from './autogenerated/autogenerated_clock_session_line_item.d.ts'

declare global {
	type DbInsertableClockSessionLineItem = AutogeneratedInsertableClockSessionLineItem
	type DbClockSessionLineItem = AutogeneratedClockSessionLineItem
}
