import type { AutogeneratedInsertableCompany, AutogeneratedCompany } from './autogenerated/autogenerated_company.d.ts'

declare global {
	type DbInsertableCompany = AutogeneratedInsertableCompany
	type DbCompany = AutogeneratedCompany
}
