import type { AutogeneratedInsertableCrewMember, AutogeneratedCrewMember } from './autogenerated/autogenerated_crew_member.ts'

declare global {
	type DbInsertableCrewMember = AutogeneratedInsertableCrewMember
	type DbCrewMember = AutogeneratedCrewMember
}
