import type { AutogeneratedInsertableCrewRegular, AutogeneratedCrewRegular } from './autogenerated/autogenerated_crew_regular.d.ts'

declare global {
	type DbInsertableCrewRegular = AutogeneratedInsertableCrewRegular
	type DbCrewRegular = AutogeneratedCrewRegular
}
