import type { AutogeneratedInsertableCrewRegularHistory, AutogeneratedCrewRegularHistory } from './autogenerated/autogenerated_crew_regular_history.d.ts'

declare global {
	type DbInsertableCrewRegularHistory = AutogeneratedInsertableCrewRegularHistory
	type DbCrewRegularHistory = AutogeneratedCrewRegularHistory
}
