import type { AutogeneratedInsertableCrew, AutogeneratedCrew } from './autogenerated/autogenerated_crew.ts'

declare global {
	type DbInsertableCrew = AutogeneratedInsertableCrew
	type DbCrew = AutogeneratedCrew
}
