import type { AutogeneratedInsertableEmployee, AutogeneratedEmployee } from './autogenerated/autogenerated_employee.d.ts'

declare global {
	type DbInsertableEmployee = AutogeneratedInsertableEmployee
	type DbEmployee = AutogeneratedEmployee
}
