import type { AutogeneratedInsertableEmployeeSession, AutogeneratedEmployeeSession } from './autogenerated/autogenerated_employee_session.d.ts'

declare global {
	type DbInsertableEmployeeSession = AutogeneratedInsertableEmployeeSession
	type DbEmployeeSession = AutogeneratedEmployeeSession
}
