import type { AutogeneratedInsertableEmployee, AutogeneratedEmployee } from './autogenerated/autogenerated_employee.d.ts'

type EmailOrLoginNameOrBoth =
	| { email: string; login_name: string | null }
	| { email: string | null; login_name: string }

declare global {
	type DbInsertableEmployee = Omit<AutogeneratedInsertableEmployee, 'email' | 'login_name'> & EmailOrLoginNameOrBoth
	type DbEmployee = Omit<AutogeneratedEmployee, 'email' | 'login_name'> & EmailOrLoginNameOrBoth
}
