import type { AutogeneratedInsertableEmployeeWorkSkill, AutogeneratedEmployeeWorkSkill } from './autogenerated/autogenerated_employee_work_skill.d.ts'

declare global {
	type DbInsertableEmployeeWorkSkill = AutogeneratedInsertableEmployeeWorkSkill
	type DbEmployeeWorkSkill = AutogeneratedEmployeeWorkSkill
}
