import type { AutogeneratedInsertableEmployeeSoftwareRole, AutogeneratedEmployeeSoftwareRole } from './autogenerated/autogenerated_employee_software_role.ts'

declare global {
	type DbInsertableEmployeeSoftwareRole = AutogeneratedInsertableEmployeeSoftwareRole
	type DbEmployeeSoftwareRole = AutogeneratedEmployeeSoftwareRole
}
