import type { AutogeneratedInsertableEstimateAvailability, AutogeneratedEstimateAvailability } from './autogenerated/autogenerated_estimate_availability.d.ts'

declare global {
	type DbInsertableEstimateAvailability = AutogeneratedInsertableEstimateAvailability
	type DbEstimateAvailability = AutogeneratedEstimateAvailability
}
