import type { FinancialNumber } from 'financial-number'
import type { AutogeneratedInsertableInvoiceLineItem, AutogeneratedInvoiceLineItem } from './autogenerated/autogenerated_invoice_line_item.d.ts'

// A rate discount and a flat discount are exclusive modes.
type LineItemDiscountFields =
	| { discount_rate: FinancialNumber; discount: null }
	| { discount_rate: null; discount: FinancialNumber | null }

declare global {
	type DbInsertableInvoiceLineItem = Omit<AutogeneratedInsertableInvoiceLineItem, keyof LineItemDiscountFields> & LineItemDiscountFields
	type DbInvoiceLineItem = Omit<AutogeneratedInvoiceLineItem, keyof LineItemDiscountFields> & LineItemDiscountFields
}
