import type { FinancialNumber } from 'financial-number'
import type { AutogeneratedInsertableInvoice, AutogeneratedInvoice } from './autogenerated/autogenerated_invoice.d.ts'

// tax_rate_id/tax_rate are null exactly when the invoice is not taxable.
type InvoiceTaxFields =
	| { taxable: true; tax_rate_id: bigint; tax_rate: FinancialNumber }
	| { taxable: false; tax_rate_id: null; tax_rate: null }

// A header discount and per-line discounts are exclusive modes.
type InvoiceDiscountFields =
	| { discount: FinancialNumber; line_item_discount_subtotal: null }
	| { discount: null; line_item_discount_subtotal: FinancialNumber | null }

type OverriddenKeys = keyof InvoiceTaxFields | keyof InvoiceDiscountFields

declare global {
	type DbInsertableInvoice = Omit<AutogeneratedInsertableInvoice, OverriddenKeys> & InvoiceTaxFields & InvoiceDiscountFields
	type DbInvoice = Omit<AutogeneratedInvoice, OverriddenKeys> & InvoiceTaxFields & InvoiceDiscountFields
}
