import type { AutogeneratedInsertableInvoiceNumber, AutogeneratedInvoiceNumber } from './autogenerated/autogenerated_invoice_number.d.ts'

declare global {
	type DbInsertableInvoiceNumber = AutogeneratedInsertableInvoiceNumber
	type DbInvoiceNumber = AutogeneratedInvoiceNumber
}
