import type { AutogeneratedInsertableItemType, AutogeneratedItemType } from './autogenerated/autogenerated_item_type.ts'

declare global {
	type DbInsertableItemType = AutogeneratedInsertableItemType
	type DbItemType = AutogeneratedItemType
}
