import type { AutogeneratedInsertableLeadSource, AutogeneratedLeadSource } from './autogenerated/autogenerated_lead_source.d.ts'

declare global {
	type DbInsertableLeadSource = AutogeneratedInsertableLeadSource
	type DbLeadSource = AutogeneratedLeadSource
}
