import type { AutogeneratedInsertableLineItemTemplate, AutogeneratedLineItemTemplate } from './autogenerated/autogenerated_line_item_template.d.ts'

declare global {
	type DbInsertableLineItemTemplate = AutogeneratedInsertableLineItemTemplate
	type DbLineItemTemplate = AutogeneratedLineItemTemplate
}
