import type { AutogeneratedInsertableLineItemTemplateWorkSkill, AutogeneratedLineItemTemplateWorkSkill } from './autogenerated/autogenerated_line_item_template_work_skill.d.ts'

declare global {
	type DbInsertableLineItemTemplateWorkSkill = AutogeneratedInsertableLineItemTemplateWorkSkill
	type DbLineItemTemplateWorkSkill = AutogeneratedLineItemTemplateWorkSkill
}
