import type { AutogeneratedInsertableMigration, AutogeneratedMigration } from './autogenerated/autogenerated_migration.d.ts'

declare global {
	type DbInsertableMigration = AutogeneratedInsertableMigration
	type DbMigration = AutogeneratedMigration
}
