import type { AutogeneratedInsertablePaymentProject, AutogeneratedPaymentProject } from './autogenerated/autogenerated_payment_project.ts'

declare global {
	type DbInsertablePaymentProject = AutogeneratedInsertablePaymentProject
	type DbPaymentProject = AutogeneratedPaymentProject
}
