import type { AutogeneratedInsertablePaymentInvoice, AutogeneratedPaymentInvoice } from './autogenerated/autogenerated_payment_invoice.d.ts'

declare global {
	type DbInsertablePaymentInvoice = AutogeneratedInsertablePaymentInvoice
	type DbPaymentInvoice = AutogeneratedPaymentInvoice
}
