import type { AutogeneratedInsertablePaymentMethod, AutogeneratedPaymentMethod } from './autogenerated/autogenerated_payment_method.d.ts'

declare global {
	type DbInsertablePaymentMethod = AutogeneratedInsertablePaymentMethod
	type DbPaymentMethod = AutogeneratedPaymentMethod
}
