import type { AutogeneratedInsertablePayment, AutogeneratedPayment } from './autogenerated/autogenerated_payment.ts'

declare global {
	type DbInsertablePayment = AutogeneratedInsertablePayment
	type DbPayment = AutogeneratedPayment
}
