import type { AutogeneratedInsertablePermission, AutogeneratedPermission } from './autogenerated/autogenerated_permission.d.ts'

type PermissionCode = 'CAN_CHANGE_WORK_ORDERS_WITHOUT_CUSTOMER_APPROVAL' | 'CAN_CREATE_CLIENT' | 'CAN_CREATE_ORDER' | 'CAN_EDIT_CLIENT' | 'CAN_EDIT_PAYMENTS' | 'CAN_ESTIMATE' | 'CAN_MANAGE_USERS' | 'CAN_QUALIFY_LEAD' | 'CAN_SET_ANY_DOCUMENT_STATUS' | 'CAN_WORK_PROJECTS'

declare global {
	type DbInsertablePermission = AutogeneratedInsertablePermission

	type DbPermission = AutogeneratedPermission & {
		code: PermissionCode
	}
}
