import type { AutogeneratedInsertablePermission, AutogeneratedPermission } from './autogenerated/autogenerated_permission.d.ts'

declare global {
	type DbInsertablePermission = AutogeneratedInsertablePermission
	type DbPermission = AutogeneratedPermission
}
