import type { AutogeneratedInsertableProjectLineItem, AutogeneratedProjectLineItem } from './autogenerated/autogenerated_project_line_item.d.ts'
import type { Temporal } from '@js-temporal/polyfill'

type DoneOrNotDone =
	| { done_at: Temporal.Instant; done_by_employee_id: bigint }
	| { done_at: null; done_by_employee_id: null }

declare global {
	type DbInsertableProjectLineItem = Omit<AutogeneratedInsertableProjectLineItem, 'done_at' | 'done_by_employee_id'> & DoneOrNotDone
	type DbProjectLineItem = Omit<AutogeneratedProjectLineItem, 'done_at' | 'done_by_employee_id'> & DoneOrNotDone
}
