import type { AutogeneratedInsertableProjectImage, AutogeneratedProjectImage } from './autogenerated/autogenerated_project_image.d.ts'

declare global {
	type DbInsertableProjectImage = AutogeneratedInsertableProjectImage
	type DbProjectImage = AutogeneratedProjectImage
}
