import type { AutogeneratedInsertableProjectCrewEmployee, AutogeneratedProjectCrewEmployee } from './autogenerated/autogenerated_project_crew_employee.d.ts'

declare global {
	type DbInsertableProjectCrewEmployee = AutogeneratedInsertableProjectCrewEmployee
	type DbProjectCrewEmployee = AutogeneratedProjectCrewEmployee
}
