import type { AutogeneratedInsertableProjectNumber, AutogeneratedProjectNumber } from './autogenerated/autogenerated_project_number.d.ts'

declare global {
	type DbInsertableProjectNumber = AutogeneratedInsertableProjectNumber
	type DbProjectNumber = AutogeneratedProjectNumber
}
