import type { AutogeneratedInsertableProjectLineItem, AutogeneratedProjectLineItem } from './autogenerated/autogenerated_project_line_item.d.ts'

declare global {
	type DbInsertableProjectLineItem = AutogeneratedInsertableProjectLineItem
	type DbProjectLineItem = AutogeneratedProjectLineItem
}
