import type { AutogeneratedInsertableProjectDocumentHistory, AutogeneratedProjectDocumentHistory } from './autogenerated/autogenerated_project_document_history.d.ts'

declare global {
	type DbInsertableProjectDocumentHistory = AutogeneratedInsertableProjectDocumentHistory
	type DbProjectDocumentHistory = AutogeneratedProjectDocumentHistory
}
