import type { AutogeneratedInsertableProjectWorkSkill, AutogeneratedProjectWorkSkill } from './autogenerated/autogenerated_project_work_skill.ts'

declare global {
	type DbInsertableProjectWorkSkill = AutogeneratedInsertableProjectWorkSkill
	type DbProjectWorkSkill = AutogeneratedProjectWorkSkill
}
