import type { AutogeneratedInsertableProjectClientApproval, AutogeneratedProjectClientApproval } from './autogenerated/autogenerated_project_client_approval.ts'

declare global {
	type DbInsertableProjectClientApproval = AutogeneratedInsertableProjectClientApproval
	type DbProjectClientApproval = AutogeneratedProjectClientApproval
}
