import type { FinancialNumber } from 'financial-number'
import type { AutogeneratedInsertableProject, AutogeneratedProject } from './autogenerated/autogenerated_project.d.ts'

// tax_rate_id/tax_rate are null exactly when the project is not taxable.
type ProjectTaxFields =
	| { taxable: true; tax_rate_id: bigint; tax_rate: FinancialNumber }
	| { taxable: false; tax_rate_id: null; tax_rate: null }

// A header discount (rate or flat) and per-line discounts are exclusive modes.
type ProjectDiscountFields =
	| { discount_rate: FinancialNumber; discount: null; line_item_discount_subtotal: null }
	| { discount_rate: null; discount: FinancialNumber; line_item_discount_subtotal: null }
	| { discount_rate: null; discount: null; line_item_discount_subtotal: FinancialNumber | null }

type OverriddenKeys = keyof ProjectTaxFields | keyof ProjectDiscountFields

declare global {
	type DbInsertableProject = Omit<AutogeneratedInsertableProject, OverriddenKeys> & ProjectTaxFields & ProjectDiscountFields
	type DbProject = Omit<AutogeneratedProject, OverriddenKeys> & ProjectTaxFields & ProjectDiscountFields
}
