import type { AutogeneratedInsertableProjectLineItemWorkSkill, AutogeneratedProjectLineItemWorkSkill } from './autogenerated/autogenerated_project_line_item_work_skill.d.ts'

declare global {
	type DbInsertableProjectLineItemWorkSkill = AutogeneratedInsertableProjectLineItemWorkSkill
	type DbProjectLineItemWorkSkill = AutogeneratedProjectLineItemWorkSkill
}
