import type { AutogeneratedInsertableProjectDocument, AutogeneratedProjectDocument } from './autogenerated/autogenerated_project_document.d.ts'

declare global {
	type DbInsertableProjectDocument = AutogeneratedInsertableProjectDocument
	type DbProjectDocument = AutogeneratedProjectDocument
}
