import type { AutogeneratedInsertableProject, AutogeneratedProject } from './autogenerated/autogenerated_project.d.ts'

declare global {
	type DbInsertableProject = AutogeneratedInsertableProject
	type DbProject = AutogeneratedProject
}
