import type { AutogeneratedInsertableProjectLineItemImage, AutogeneratedProjectLineItemImage } from './autogenerated/autogenerated_project_line_item_image.d.ts'

declare global {
	type DbInsertableProjectLineItemImage = AutogeneratedInsertableProjectLineItemImage
	type DbProjectLineItemImage = AutogeneratedProjectLineItemImage
}
