import type { FinancialNumber } from 'financial-number'
import type { AutogeneratedInsertableProject, AutogeneratedProject } from './autogenerated/autogenerated_project.d.ts'

// tax_rate_id/tax_rate are null exactly when the project is not taxable.
type ProjectTaxFields =
	| { taxable: true; tax_rate_id: bigint; tax_rate: FinancialNumber }
	| { taxable: false; tax_rate_id: null; tax_rate: null }

declare global {
	type DbInsertableProject = Omit<AutogeneratedInsertableProject, keyof ProjectTaxFields> & ProjectTaxFields
	type DbProject = Omit<AutogeneratedProject, keyof ProjectTaxFields> & ProjectTaxFields
}
