import type { AutogeneratedInsertableProjectCrew, AutogeneratedProjectCrew } from './autogenerated/autogenerated_project_crew.d.ts'
import type { Temporal } from '@js-temporal/polyfill'

type ProjectCrewSchedule =
	| { day_order: bigint, start_time: null }
	| { day_order: null, start_time: Temporal.PlainTime }

declare global {
	type DbInsertableProjectCrew = Omit<AutogeneratedInsertableProjectCrew, 'day_order' | 'start_time'> & ProjectCrewSchedule
	type DbProjectCrew = Omit<AutogeneratedProjectCrew, 'day_order' | 'start_time'> & ProjectCrewSchedule
}
