import type { FinancialNumber } from 'financial-number'
import type { AutogeneratedInsertableProjectLineItem, AutogeneratedProjectLineItem } from './autogenerated/autogenerated_project_line_item.d.ts'
import type { Temporal } from '@js-temporal/polyfill'

type DoneOrNotDone =
	| { done_at: Temporal.Instant; done_by_employee_id: bigint }
	| { done_at: null; done_by_employee_id: null }

// A rate discount and a flat discount are exclusive modes.
type LineItemDiscountFields =
	| { discount_rate: FinancialNumber; discount: null }
	| { discount_rate: null; discount: FinancialNumber | null }

type OverriddenKeys = keyof DoneOrNotDone | keyof LineItemDiscountFields

declare global {
	type DbInsertableProjectLineItem = Omit<AutogeneratedInsertableProjectLineItem, OverriddenKeys> & DoneOrNotDone & LineItemDiscountFields
	type DbProjectLineItem = Omit<AutogeneratedProjectLineItem, OverriddenKeys> & DoneOrNotDone & LineItemDiscountFields
}
