import type { AutogeneratedInsertableProjectDeclineReason, AutogeneratedProjectDeclineReason } from './autogenerated/autogenerated_project_decline_reason.d.ts'

declare global {
	type DbInsertableProjectDeclineReason = AutogeneratedInsertableProjectDeclineReason
	type DbProjectDeclineReason = AutogeneratedProjectDeclineReason
}
