import type { AutogeneratedInsertableSoftwareRole, AutogeneratedSoftwareRole } from './autogenerated/autogenerated_software_role.d.ts'

declare global {
	type DbInsertableSoftwareRole = AutogeneratedInsertableSoftwareRole
	type DbSoftwareRole = AutogeneratedSoftwareRole
}
