import type { AutogeneratedInsertableSoftwareRolePermission, AutogeneratedSoftwareRolePermission } from './autogenerated/autogenerated_software_role_permission.ts'

declare global {
	type DbInsertableSoftwareRolePermission = AutogeneratedInsertableSoftwareRolePermission
	type DbSoftwareRolePermission = AutogeneratedSoftwareRolePermission
}
