import type { AutogeneratedInsertableTaxRate, AutogeneratedTaxRate } from './autogenerated/autogenerated_tax_rate.d.ts'

declare global {
	type DbInsertableTaxRate = AutogeneratedInsertableTaxRate
	type DbTaxRate = AutogeneratedTaxRate
}
