import type { AutogeneratedInsertableTimeEntry, AutogeneratedTimeEntry } from './autogenerated/autogenerated_time_entry.d.ts'

declare global {
	type DbInsertableTimeEntry = AutogeneratedInsertableTimeEntry
	type DbTimeEntry = AutogeneratedTimeEntry
}
