import type { AutogeneratedInsertableWorkSkill, AutogeneratedWorkSkill } from './autogenerated/autogenerated_work_skill.ts'

declare global {
	type DbInsertableWorkSkill = AutogeneratedInsertableWorkSkill
	type DbWorkSkill = AutogeneratedWorkSkill
}
